import * as fs from "fs";
import { Settings } from "../settings";
import { System, Log, SystemContext, Content } from "./system";
import { WEATHER_REGIONS, WEATHER_CATALOG, WeatherRegionDef, WeatherChance } from "./weatherRegions";
import { writeFileAtomic } from "./fileUtil";
import { every } from "./timers";
import { onlineSnapshot } from "./onlineSnapshot";
import { espmFieldFormIds } from "./formIdUtil";

// The ScampServer / `mp` API is untyped here, same convention as spawn.ts.
type Mp = any;

// Per-region weather: the server rolls one weather per region for 30-90 real minutes and every client standing in it shows that weather.
// Regions are the plugins' REGN weather lists (weatherRegions.ts, generated by misc/gen-weather-regions.py), or ./weather-regions.json when present.
// A player's region is the first region in priority order whose polygon holds them in a listed world; indoors they keep their last exterior
// region (mirrored to private.weatherRegion so a relog in an inn keeps it); in an unlisted world (Sovngarde, the Soul Cairn) and in an interior
// that draws such a world's sky (the Hall of Valor, the Black Book realms) they get none and the vanilla sky runs, without losing the stored region.
// Durations use the box clock (Date.now), never the game calendar TimeSystem drives.
//
//   Server -> Client: { customPacketType: "weather", region, name, weatherId, weather, endsAt, transition, gameSettings }  region null: release the override
//   Client -> Server: { customPacketType: "weatherRequest" }  the current weather again, after a load screen; answered at once
// A packet goes out when a player's region, its weather or its start changed: from the 2 s poll (travel, rolls), at once to a whole region
// with transition "instant" when an admin forces or clears it, and at once as the answer to weatherRequest.
//
// server-settings.json keys (all optional):
//   weatherEnabled       false switches the sync off (default true)
//   weatherMinMinutes    shortest weather in real minutes (default 30)
//   weatherMaxMinutes    longest (default 90)
//   weatherTransition    how a client changes to a rolled weather: "accelerate" (default: a fade still running is hurried first), "normal" or "instant"
//   weatherGameSettings  { "fWeatherTransMin": .., "fWeatherTransMax": .., "fWeatherTransAccel": .. } floats every client applies once, over DEFAULT_GAME_SETTINGS
// State: ./weather-state.json, one entry per region { weatherDesc, weatherId, startedAt, endsAt, forced }, rewritten atomically on every change.

const STATE_FILE = "./weather-state.json";
const OVERRIDE_FILE = "./weather-regions.json";
const REGION_PROP = "private.weatherRegion";
const POLL_MS = 2000;
// The poll works a player's region out again after a cell change or this much travel on the x/y plane
const RESOLVE_MOVE = 1024;
const DEFAULT_MIN_MINUTES = 30;
const DEFAULT_MAX_MINUTES = 90;
const MAX_MINUTES = 1440;
const TRANSITIONS = ["accelerate", "normal", "instant"];
// A fade lasts fWeatherTransMin to fWeatherTransMax game hours (vanilla 0.01 and 0.25 at timescale 20); a twentieth keeps its 2 to 45 s on the 1:1 clock
const DEFAULT_GAME_SETTINGS: Record<string, number> = { fWeatherTransMin: 0.0005, fWeatherTransMax: 0.0125 };
// Utility weathers, listed after the real ones in the admin picker
const CATALOG_LAST = /^(FX|Editor|TEST|WorldMap)/i;

interface RegionState {
  weatherDesc: string;
  weatherId: number;
  startedAt: number;
  // 0: until cleared
  endsAt: number;
  forced: boolean;
}

interface WeatherEntry {
  desc: string;
  edid: string;
  kind: string;
  id: number;
}

interface Region {
  def: WeatherRegionDef;
  weathers: Array<WeatherChance & { id: number }>;
  state: RegionState;
}

interface Area {
  region: Region;
  poly: number[][] | null;
}

export interface WeatherRegionRow {
  id: string;
  name: string;
  weather: string;
  weatherDesc: string;
  endsAt: number;
  forced: boolean;
  players: number;
  here: boolean;
  weathers: WeatherChance[];
}

export interface WeatherCatalogRow {
  desc: string;
  edid: string;
  kind: string;
}

// Even-odd rule on the region polygon, x/y in world units
export const pointInPolygon = (poly: number[][], x: number, y: number): boolean => {
  let inside = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [xi, yi] = poly[i];
    const [xj, yj] = poly[j];
    if ((yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
};

export class WeatherSystem implements System {
  systemName = "WeatherSystem";
  constructor(private log: Log) { }

  private enabled = true;
  private minMinutes = DEFAULT_MIN_MINUTES;
  private maxMinutes = DEFAULT_MAX_MINUTES;
  private transition = "accelerate";
  private gameSettings = DEFAULT_GAME_SETTINGS;
  private mp: Mp | null = null;
  private regions = new Map<string, Region>();
  // Areas per world id, in lookup order
  private worldAreas = new Map<number, Area[]>();
  private byDesc = new Map<string, WeatherEntry>();
  // Unlisted worlds and interiors by whether they keep their own sky, and the world an interior's sky region (CELL XCCM) belongs to
  private skies = new Map<number, { own: boolean; world: number }>();
  private lastRegion = new Map<number, string | null>();
  private lastSent = new Map<number, string>();
  // Where the poll last worked out each actor's region
  private resolvedAt = new Map<number, { cell: number; x: number; y: number }>();

  async initAsync(ctx: SystemContext): Promise<void> {
    const all = (await Settings.get()).allSettings as Record<string, any> | null;
    this.readSettings(all);
    if (!this.enabled) {
      this.log("WeatherSystem: disabled (weatherEnabled false)");
      return;
    }
    const mp = ctx.svr as Mp;
    this.mp = mp;
    for (const entry of WEATHER_CATALOG) this.resolveWeather(mp, entry);
    const defs = this.loadDefs();
    for (const def of defs) {
      const weathers = def.weathers.map(w => ({ ...w, id: this.resolveWeather(mp, w)?.id ?? 0 })).filter(w => w.id);
      if (!weathers.length) {
        this.log(`WeatherSystem: region ${def.id} has no usable weather, dropped`);
        continue;
      }
      const region: Region = { def, weathers, state: { weatherDesc: "", weatherId: 0, startedAt: 0, endsAt: 0, forced: false } };
      let worlds = 0;
      for (const area of def.areas) {
        let worldId = 0;
        try { worldId = mp.getIdFromDesc(area.world) >>> 0; } catch { }
        if (!worldId) {
          this.log(`WeatherSystem: region ${def.id}: world ${area.world} unknown, area dropped`);
          continue;
        }
        const list = this.worldAreas.get(worldId) ?? [];
        list.push({ region, poly: area.poly && area.poly.length >= 3 ? area.poly : null });
        this.worldAreas.set(worldId, list);
        worlds++;
      }
      if (worlds) this.regions.set(def.id, region);
    }
    const { kept, rolled } = this.loadState();
    this.log(`WeatherSystem: ${this.regions.size} regions over ${this.worldAreas.size} worlds, ${this.byDesc.size} catalog weathers, ${this.minMinutes}-${this.maxMinutes} min, transition ${this.transition}; ${STATE_FILE}: ${kept} kept, ${rolled} rolled`);
    every("weather", POLL_MS, () => this.poll(ctx));
  }

  private readSettings(all: Record<string, any> | null): void {
    if (all?.["weatherEnabled"] === false) this.enabled = false;
    const min = Number(all?.["weatherMinMinutes"]);
    const max = Number(all?.["weatherMaxMinutes"]);
    if (Number.isFinite(min) && min >= 1 && min <= MAX_MINUTES) this.minMinutes = min;
    if (Number.isFinite(max) && max >= this.minMinutes && max <= MAX_MINUTES) this.maxMinutes = max;
    if (this.maxMinutes < this.minMinutes) this.maxMinutes = this.minMinutes;
    const transition = String(all?.["weatherTransition"] ?? "");
    if (TRANSITIONS.includes(transition)) this.transition = transition;
    const gs = all?.["weatherGameSettings"];
    if (gs && typeof gs === "object" && !Array.isArray(gs)) {
      const out = { ...DEFAULT_GAME_SETTINGS };
      for (const [k, v] of Object.entries(gs)) {
        if (/^fWeatherTrans/.test(k) && Number.isFinite(Number(v))) out[k] = Number(v);
      }
      this.gameSettings = out;
    }
  }

  // The generated list, unless a hand-edited ./weather-regions.json of the same shape sits next to the server
  private loadDefs(): WeatherRegionDef[] {
    let raw: string;
    try { raw = fs.readFileSync(OVERRIDE_FILE, "utf8"); } catch { return WEATHER_REGIONS; }
    try {
      const parsed = JSON.parse(raw);
      const defs = (Array.isArray(parsed) ? parsed : []).filter((d: any) =>
        d && typeof d.id === "string" && d.id && Array.isArray(d.areas) && Array.isArray(d.weathers)
        && d.areas.every((a: any) => a && typeof a.world === "string" && (a.poly === undefined || Array.isArray(a.poly)))
        && d.weathers.every((w: any) => w && typeof w.desc === "string" && Number(w.chance) > 0));
      this.log(`WeatherSystem: ${OVERRIDE_FILE} overrides the generated regions, ${defs.length} of ${Array.isArray(parsed) ? parsed.length : 0} entries usable`);
      return defs.map((d: any) => ({
        id: d.id, name: String(d.name || d.id), edid: String(d.edid || ""), priority: Number(d.priority) || 0, areas: d.areas,
        weathers: d.weathers.map((w: any) => ({ desc: w.desc, edid: String(w.edid || ""), chance: Number(w.chance) })),
      }));
    } catch (e) {
      this.log(`WeatherSystem: ${OVERRIDE_FILE} is unreadable, using the generated regions: ${e}`);
      return WEATHER_REGIONS;
    }
  }

  private resolveWeather(mp: Mp, w: { desc: string; edid: string; kind?: string }): WeatherEntry | null {
    const key = w.desc.toLowerCase();
    const known = this.byDesc.get(key);
    if (known) return known;
    let id = 0;
    let type = "";
    try {
      id = mp.getIdFromDesc(w.desc) >>> 0;
      type = String(mp.lookupEspmRecordById(id)?.record?.type ?? "");
    } catch { }
    if (!id || type !== "WTHR") {
      this.log(`WeatherSystem: ${w.desc} (${w.edid}) is not a WTHR in the load order, dropped`);
      return null;
    }
    const entry = { desc: w.desc, edid: w.edid, kind: w.kind ?? "", id };
    this.byDesc.set(key, entry);
    return entry;
  }

  // Running or forced entries survive a restart; everything else rolls fresh
  private loadState(): { kept: number; rolled: number } {
    let saved: Record<string, any> = {};
    try {
      const parsed = JSON.parse(fs.readFileSync(STATE_FILE, "utf8"));
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) saved = parsed;
    } catch (e: any) {
      if (e?.code !== "ENOENT") this.log(`WeatherSystem: ${STATE_FILE} is unreadable, rolling every region: ${e}`);
    }
    const now = Date.now();
    let kept = 0;
    let rolled = 0;
    for (const region of this.regions.values()) {
      const s = saved[region.def.id];
      const weather = s && typeof s.weatherDesc === "string" ? this.byDesc.get(s.weatherDesc.toLowerCase()) : undefined;
      const endsAt = Number(s?.endsAt);
      const forced = s?.forced === true;
      // endsAt 0 is a forced weather held until cleared; a timed one that ran out while the server was down rolls like any other
      const running = Number.isFinite(endsAt) && (endsAt === 0 ? forced : endsAt > now);
      if (weather && running) {
        region.state = { weatherDesc: weather.desc, weatherId: weather.id, startedAt: Number(s.startedAt) || now, endsAt, forced };
        kept++;
      } else {
        region.state = this.roll(region, now);
        rolled++;
      }
    }
    this.saveState();
    return { kept, rolled };
  }

  private saveState(): void {
    const out: Record<string, RegionState> = {};
    for (const [id, region] of this.regions) out[id] = region.state;
    try {
      writeFileAtomic(STATE_FILE, JSON.stringify(out, null, 1));
    } catch (e) {
      this.log(`WeatherSystem: ${STATE_FILE} write failed: ${e}`);
    }
  }

  // Weighted pick that avoids repeating the current weather, for min..max minutes
  private roll(region: Region, now: number): RegionState {
    const current = region.state.weatherDesc;
    const others = region.weathers.filter(w => w.desc !== current);
    const pool = others.length ? others : region.weathers;
    let left = Math.random() * pool.reduce((sum, w) => sum + w.chance, 0);
    let pick = pool[pool.length - 1];
    for (const w of pool) {
      left -= w.chance;
      if (left < 0) {
        pick = w;
        break;
      }
    }
    const minutes = this.minMinutes + Math.random() * (this.maxMinutes - this.minMinutes);
    this.log(`[weather] ${region.def.id}: ${pick.edid} for ${Math.round(minutes)} min`);
    return { weatherDesc: pick.desc, weatherId: pick.id, startedAt: now, endsAt: now + Math.round(minutes * 60000), forced: false };
  }

  customPacket(userId: number, type: string, _content: Content, ctx: SystemContext): void {
    if (type !== "weatherRequest" || !this.enabled) return;
    this.lastSent.delete(userId);
    const mp = ctx.svr as Mp;
    try {
      const actorId = mp.getUserActor(userId);
      if (actorId) this.sync(mp, userId, this.regionNow(mp, actorId));
    } catch { /* the poll answers */ }
  }

  disconnect(userId: number, ctx: SystemContext): void {
    this.lastSent.delete(userId);
    try {
      const actorId = (ctx.svr as Mp).getUserActor(userId);
      if (actorId) {
        this.lastRegion.delete(actorId);
        this.resolvedAt.delete(actorId);
      }
    } catch { }
  }

  poll(ctx: SystemContext): void {
    if (!this.enabled) return;
    const mp = ctx.svr as Mp;
    const now = Date.now();
    let changed = false;
    for (const region of this.regions.values()) {
      const s = region.state;
      if (s.endsAt && s.endsAt <= now) {
        if (s.forced) this.log(`[weather] ${region.def.id}: forced ${this.edidOf(s.weatherDesc)} ran out`);
        region.state = this.roll(region, now);
        changed = true;
      }
    }
    if (changed) this.saveState();
    for (const { actorId, userId, cell, pos } of onlineSnapshot(mp).players) {
      if (userId >= 0) this.sync(mp, userId, this.polledRegion(mp, actorId, cell, pos));
    }
  }

  // Sends the region's weather, or the release without one, unless the user already holds exactly that
  private sync(mp: Mp, userId: number, regionId: string | null, transition = this.transition): boolean {
    const region = regionId ? this.regions.get(regionId) : undefined;
    const key = region ? `${regionId}|${region.state.weatherId}|${region.state.startedAt}` : "none";
    if (this.lastSent.get(userId) === key) return false;
    this.lastSent.set(userId, key);
    const packet: Record<string, unknown> = { customPacketType: "weather", region: region ? regionId : null, transition, gameSettings: this.gameSettings };
    if (region) {
      packet["name"] = region.def.name;
      packet["weatherId"] = region.state.weatherId;
      packet["weather"] = this.edidOf(region.state.weatherDesc);
      packet["endsAt"] = region.state.endsAt;
    }
    try { mp.sendCustomPacket(userId, JSON.stringify(packet)); } catch { }
    return true;
  }

  // An admin's change shows at once and without a fade for everyone the poll last placed in the region
  private pushNow(regionId: string): void {
    const mp = this.mp;
    if (!mp) return;
    let sent = 0;
    for (const { actorId, userId } of onlineSnapshot(mp).players) {
      if (userId >= 0 && this.lastRegion.get(actorId) === regionId && this.sync(mp, userId, regionId, "instant")) sent++;
    }
    this.log(`[weather] ${regionId}: ${this.edidOf(this.regions.get(regionId)?.state.weatherDesc ?? "")} set outright for ${sent} player(s)`);
  }

  private edidOf(desc: string): string {
    return this.byDesc.get(desc.toLowerCase())?.edid ?? desc;
  }

  // Editor id of a catalog desc or editor id, the value itself when unknown
  weatherName(weather: string): string {
    return this.edidOf(weather);
  }

  regionName(regionId: string): string {
    return this.regions.get(regionId)?.def.name ?? regionId;
  }

  // The weather the region shows now, forced or rolled; null for an unknown region or with the sync off
  currentWeatherOf(regionId: string): { id: number; edid: string; kind: string } | null {
    const state = this.enabled ? this.regions.get(regionId)?.state : undefined;
    const entry = state?.weatherDesc ? this.byDesc.get(state.weatherDesc.toLowerCase()) : undefined;
    return entry ? { id: entry.id, edid: entry.edid, kind: entry.kind } : null;
  }

  // An unlisted world, and an interior whose sky region (CELL XCCM) belongs to one, keep their own sky
  private keepsOwnSky(mp: Mp, place: number): boolean {
    return this.skyOf(mp, place).own;
  }

  private skyOf(mp: Mp, place: number): { own: boolean; world: number } {
    let sky = this.skies.get(place);
    if (!sky) {
      sky = { own: false, world: 0 };
      try {
        const rec = mp.lookupEspmRecordById(place);
        const [skyRegion] = espmFieldFormIds(rec, "XCCM");
        const [world] = skyRegion ? espmFieldFormIds(mp.lookupEspmRecordById(skyRegion), "WNAM") : [];
        sky.world = world || 0;
        sky.own = String(rec?.record?.type ?? "") === "WRLD" || (!!world && !this.worldAreas.has(world));
      } catch { }
      this.skies.set(place, sky);
    }
    return sky;
  }

  // The last region (exact lookups refresh it too) until the actor changes cell or travels RESOLVE_MOVE from the last resolve
  private polledRegion(mp: Mp, actorId: number, cell: number, pos: readonly number[]): string | null {
    const at = this.resolvedAt.get(actorId);
    if (at && at.cell === cell && this.lastRegion.has(actorId) && (pos[0] - at.x) ** 2 + (pos[1] - at.y) ** 2 < RESOLVE_MOVE ** 2) {
      return this.lastRegion.get(actorId) ?? null;
    }
    this.resolvedAt.set(actorId, { cell, x: pos[0], y: pos[1] });
    return this.regionFor(mp, actorId, cell, pos);
  }

  // The region at place and pos in a listed world, none where the place keeps its own sky; with place 0 (unknown), indoors, or outside every polygon, the last one the actor stood in
  private regionFor(mp: Mp, actorId: number, place: number, pos: readonly number[] | null): string | null {
    if (!place) return this.lastKnown(mp, actorId);
    const areas = this.worldAreas.get(place);
    if (areas) {
      if (!pos) return this.lastKnown(mp, actorId);
      for (const a of areas) {
        if (!a.poly || pointInPolygon(a.poly, pos[0], pos[1])) return this.remember(mp, actorId, a.region.def.id);
      }
      return this.lastKnown(mp, actorId);
    }
    return this.keepsOwnSky(mp, place) ? this.remember(mp, actorId, null) : this.lastKnown(mp, actorId, place);
  }

  // The current region, or the stored one after a relog or a place with its own sky; an interior with neither (a character whose region a realm
  // erased before fba155e7) takes a region of the world its sky region belongs to, unstored, so the client holds the clear sky indoors
  private lastKnown(mp: Mp, actorId: number, interior = 0): string | null {
    const current = this.lastRegion.get(actorId);
    if (current) return current;
    let saved: unknown = null;
    try { saved = mp.get(actorId, REGION_PROP); } catch { }
    const id = typeof saved === "string" && this.regions.has(saved) ? saved : null;
    this.lastRegion.set(actorId, id);
    if (id || !interior) return id;
    const areas = this.worldAreas.get(this.skyOf(mp, interior).world) ?? [...this.worldAreas.values()][0];
    return areas?.[0]?.region.def.id ?? null;
  }

  private remember(mp: Mp, actorId: number, id: string | null): string | null {
    if (this.lastRegion.has(actorId) && this.lastRegion.get(actorId) === id) return id;
    this.lastRegion.set(actorId, id);
    if (id) try { mp.set(actorId, REGION_PROP, id); } catch { }
    return id;
  }

  // ── Admin API (AdminSystem's Weather sub-tab) ─────────────────────────────

  regionOf(mp: Mp, actorId: number): string | null {
    return this.enabled ? this.regionNow(mp, actorId) : null;
  }

  private regionNow(mp: Mp, actorId: number): string | null {
    let place = 0;
    let pos: number[] | null = null;
    try {
      place = mp.getActorCellOrWorld(actorId) >>> 0;
      pos = mp.getActorPos(actorId);
    } catch { /* falls back to the last known region */ }
    return this.regionFor(mp, actorId, place, pos);
  }

  listRegions(mp: Mp, hereActorId: number): WeatherRegionRow[] {
    if (!this.enabled) return [];
    const here = this.regionNow(mp, hereActorId);
    const counts = new Map<string, number>();
    for (const id of onlineSnapshot(mp).byActor.keys()) {
      const r = this.lastRegion.get(id);
      if (r) counts.set(r, (counts.get(r) ?? 0) + 1);
    }
    return [...this.regions.values()].map(({ def, state, weathers }) => ({
      id: def.id,
      name: def.name,
      weather: this.edidOf(state.weatherDesc),
      weatherDesc: state.weatherDesc,
      endsAt: state.endsAt,
      forced: state.forced,
      players: counts.get(def.id) ?? 0,
      here: here === def.id,
      weathers: weathers.map(({ desc, edid, chance }) => ({ desc, edid, chance })),
    }));
  }

  catalog(): WeatherCatalogRow[] {
    const rows = [...this.byDesc.values()].map(({ desc, edid, kind }) => ({ desc, edid, kind }));
    const rank = (r: WeatherCatalogRow) => (CATALOG_LAST.test(r.edid) ? 1 : 0);
    return rows.sort((a, b) => rank(a) - rank(b) || a.edid.localeCompare(b.edid));
  }

  // Holds the weather on the region until cleared, or for minutes (1..1440); a refusal comes back as text
  force(regionId: string, weather: string, minutes: number | null): string | null {
    const region = this.regions.get(regionId);
    if (!region) return "Unknown region";
    const key = String(weather).toLowerCase();
    const entry = this.byDesc.get(key) ?? [...this.byDesc.values()].find(w => w.edid.toLowerCase() === key);
    if (!entry) return "Unknown weather";
    if (minutes !== null && (!Number.isInteger(minutes) || minutes < 1 || minutes > MAX_MINUTES)) return `Minutes must be a whole number between 1 and ${MAX_MINUTES}, or blank`;
    const now = Date.now();
    region.state = { weatherDesc: entry.desc, weatherId: entry.id, startedAt: now, endsAt: minutes ? now + minutes * 60000 : 0, forced: true };
    this.saveState();
    this.pushNow(regionId);
    return null;
  }

  clear(regionId: string): string | null {
    const region = this.regions.get(regionId);
    if (!region) return "Unknown region";
    region.state = this.roll(region, Date.now());
    this.saveState();
    this.pushNow(regionId);
    return null;
  }
}
