'use strict'

const serverSettings = [
  // Identity
  { key: 'name',        label: 'Server name',  type: 'text',   group: 'Identity', help: 'Public name shown in the launcher / master list.' },
  { key: 'port',        label: 'Game port (UDP)', type: 'number', group: 'Identity', help: 'RakNet game port.' },
  { key: 'maxPlayers',  label: 'Max connections', type: 'number', group: 'Identity', help: 'RakNet connection cap including the queue room, at most the native MAX_PLAYERS (1300). To test the queue lower Play slots, never this: a connection above this number is refused before the queue sees it.' },
  { key: 'playerSlots', label: 'Play slots',   type: 'number', group: 'Identity', help: 'Verified logins that may play at once; logins above it wait in the queue up to Max connections. Empty = Max connections (queue off). Read at boot.' },
  { key: 'queueGraceMs', label: 'Queue grace (ms)', type: 'number', group: 'Identity', help: 'How long a disconnected player keeps their slot or queue place. Default 120000.' },
  { key: 'queueStaffBypass', label: 'Staff skip the queue', type: 'bool', group: 'Identity', help: 'On (default, also when unset): adminRoles tiers, adminRoleIds and adminProfileIds never wait. Turn off to test the queue with a staff account. Read at boot.' },
  { key: 'lang',        label: 'Language',     type: 'select', group: 'Identity',
    options: ['english', 'russian', 'german', 'french', 'spanish', 'italian', 'polish', 'chinese', 'japanese'] },

  // Networking
  { key: 'listenHost',   label: 'Listen host',    type: 'text', group: 'Networking', placeholder: '0.0.0.0', help: 'Bind address for game (RakNet) traffic.' },
  { key: 'uiListenHost', label: 'UI listen host', type: 'text', group: 'Networking', placeholder: '0.0.0.0', help: 'Bind address for the HTTP/UI port.' },
  { key: 'ip',           label: 'Advertised IP',  type: 'text', group: 'Networking', help: 'Public IP advertised to clients (NAT).' },

  // Mode & auth
  { key: 'offlineMode', label: 'Offline mode',  type: 'bool', group: 'Mode & auth', help: 'When on, any profile id may connect; master/masterKey are ignored.' },
  { key: 'master',      label: 'Master URL',    type: 'text', group: 'Mode & auth', help: 'Master API URL for online-mode session validation. Empty = offline.' },
  { key: 'masterKey',   label: 'Master key',    type: 'secret', group: 'Mode & auth', help: 'Public server id, not a secret: players receive it via /api/serverinfo and the launcher. The backend reads it from here.' },
  { key: 'masterApiAuthToken', label: 'Master API auth token', type: 'secret', group: 'Mode & auth', help: 'Private secret sent as X-Auth-Token on heartbeats, bans and purchases. The backend reads it from here.' },
  { key: 'enableConsoleCommandsForAll', label: 'Console commands for all (keep off)', type: 'bool', group: 'Mode & auth', help: 'Must stay off. The console is disabled on this server; turning this on skips the admin check and gives every player additem, placeatme and the other server console commands.' },

  // Gameplay
  { key: 'characterSelect',         label: 'Character select',      type: 'bool',   group: 'Gameplay', help: 'Show the character-select screen on join.' },
  { key: 'characterSelectMaxCharacters', label: 'Max characters',   type: 'number', group: 'Gameplay', help: 'Character slots per player when character select is on (1-10, default 3).' },
  { key: 'npcEnabled',              label: 'NPCs enabled',          type: 'bool',   group: 'Gameplay' },
  { key: 'masteryResetsPerCharacter', label: 'Profession resets per character', type: 'number', group: 'Gameplay', placeholder: '1', help: 'How many times a player may set a craft aside from the profession menu on one character; the hours go with it. With multiclassing one count is shared by all slots and a reset clears one slot. Read at boot. Default 1.' },
  { key: 'masteryHourBank',         label: 'Profession hour bank',  type: 'number', group: 'Gameplay', placeholder: '2', help: 'Hours that extra crafts inside an already counted hour may bank, per craft slot; each banked hour is counted after another hour online with no counted work. 0 turns the bank off. Read at boot. Default 2.' },
  { key: 'masterySlots',            label: 'Craft slots (multiclassing)', type: 'json', group: 'Gameplay', help: 'Profession slots in pick order, 1 to 3: [{ name, cap, rankHours }]. cap is a rank name or index from Novice to Legendary; rankHours the hours for each rank from Novice (the primary defaults to 0 plus masteryRankHours). Empty or one entry (the default [{ "name": "Primary", "cap": "Legendary" }]) is multiclassing off, records kept. Test: Secondary to Adept at [20, 60], Tertiary to Novice at [20]. Protected: Migrate settings never copies it to live. Read at boot.' },
  { key: 'masterySlotKits',         label: 'Sub-slot kits',         type: 'bool',   group: 'Gameplay', help: 'On (default): a secondary or tertiary pick hands over that craft\'s kit items (masteryKits), never gold, once per craft per character, none when the primary kit was that craft\'s. Read at boot.' },
  { key: 'securityAlertChannelId',  label: 'Security alert channel', type: 'text', group: 'Gameplay', help: 'Discord channel id where the backend posts every new Security tab alert (ban evasion, gold spawning). Read live. Empty posts nothing.' },
  { key: 'needsFatigueEnabled',     label: 'Fatigue enabled',       type: 'bool', group: 'Gameplay', help: 'Off makes every craft, gather, kill and cast cost no fatigue; hunger keeps running. Read at boot. Default on.' },
  { key: 'needsFatigueOfflinePerHour', label: 'Fatigue refill per offline hour', type: 'number', group: 'Gameplay', placeholder: '1', help: 'Share of the fatigue bar refilled per hour logged out, added at login and capped at a full bar. 1 = 100% an hour, the online rate; 0 turns it off. Read at boot. Default 1.' },
  { key: 'torchBurnMinutes',        label: 'Torch burn (minutes)',  type: 'number', group: 'Gameplay', placeholder: '15', help: 'Minutes of use after which a held torch burns out and one is taken from the inventory; the burn carries over relogs. 0 turns it off. Read at boot. Default 15.' },
  { key: 'goldAlertThreshold',      label: 'Gold alert threshold',  type: 'number', group: 'Gameplay', placeholder: '5000', help: 'Gold a character may gain within 10 seconds before the Security tab gets a Gold Spawning alert. 0 disables it. Read at boot. Default 5000.' },
  { key: 'isPapyrusHotReloadEnabled', label: 'Papyrus hot reload',  type: 'bool',   group: 'Gameplay', help: 'Reload compiled .pex scripts on change.' },
  { key: 'enableGamemodeDataUpdatesBroadcast', label: 'Broadcast gamemode updates', type: 'bool', group: 'Gameplay', help: 'Push gamemode script updates to connected clients.' },
  { key: 'locale',                  label: 'Locale file',           type: 'text',   group: 'Gameplay', help: 'File in data/localization (no .json) for M.GetText().' },
  { key: 'manaclesFormId',          label: 'Manacles item',         type: 'text',   group: 'Gameplay', help: 'Form id (number or "0x..." string) of the item a captor must hold to restrain a player. Defaults to vanilla prisoner cuffs 0x0005DC02.' },
  { key: 'captiveAnimEvent',        label: 'Captive anim event',    type: 'text',   group: 'Gameplay', help: 'Behaviour-graph event played on a restrained player. Leave empty for the default bound-hands pose.' },
  { key: 'carrierAnimEvent',        label: 'Carrier anim event',    type: 'text',   group: 'Gameplay', help: 'Behaviour-graph event played on a player carrying someone. Leave empty for the default hold pose.' },
  { key: 'startingItems',           label: 'Starting items',        type: 'json',   group: 'Gameplay', help: 'Kit granted to fresh characters: [{ baseId, count }]. baseId as a number or "0x..." string. Default: the miner clothes; the gold comes with the first profession kit (masteryKitGold). Gold (0x0000000f) listed here is granted once per slot, and that character\'s profession kit then comes without gold. Wearable kit items are equipped when character creation finishes.' },
  { key: 'playersInheritBaseSpells', label: 'Players inherit base spells', type: 'bool', group: 'Gameplay', help: 'On (default): player characters carry the Player record\'s castable spells (Flames, Healing) and their race\'s greater power. Off: characters start without them; abilities, racial passives, lesser powers (Night Eye) and spells learned from tomes stay. Read by the native server at boot.' },
  { key: 'logoutGraceMs',           label: 'Logout grace (ms)',     type: 'number', group: 'Gameplay', help: 'How long a disconnected body stays killable in the world before despawning. Default 300000.' },
  { key: 'respawnSeconds',          label: 'Respawn seconds',       type: 'number', group: 'Gameplay', help: 'Bleedout/respawn timer applied to players (gamemode). Default 15.' },
  { key: 'afkKickMinutes',          label: 'AFK kick (minutes)',    type: 'number', group: 'Gameplay', help: 'Minutes without movement, chat, or voice before an idle player is kicked. Players still in character creation are never kicked. 0 disables. Default 20.' },
  { key: 'afkWarnMinutes',          label: 'AFK warning (minutes)', type: 'number', group: 'Gameplay', help: 'Minutes before the AFK kick to warn the player in chat. Default 1.' },
  { key: 'regenerationMultiplier',  label: 'Regen multiplier',      type: 'number', group: 'Gameplay', help: 'Scales the health/magicka/stamina regen the server accepts from clients. 1 = race-record rates, 0 = no natural regen. Needs a native rebuild to change engine behavior; the setting itself is read at boot.' },
  { key: 'healthRegenerationMultiplier', label: 'Health regen multiplier', type: 'number', group: 'Gameplay', help: 'Takes the place of Regen multiplier for health only; magicka and stamina keep it. 0 refuses every health increase a client reports (potions, food and Restoration still heal), the server half of No health regeneration. Empty (default) = health follows Regen multiplier. Protected: Migrate settings never carries it to live. Needs a native server build from ea63f69a or later. Read at boot.' },
  { key: 'npcBlockedDamageShare',   label: 'NPC blocked damage share', type: 'number', group: 'Gameplay', help: 'Share of an NPC\'s weapon hit that still lands when a player blocks it, 0 to 1. Default 0.2 (blocking is 80% effective against NPCs); 0 restores full blocks. A player\'s hit on a blocking player stays fully blocked, NPCs blocking are unchanged. Under the rebalance formula the same share of the NPC\'s damage after DT lands, and a broken shield lets the larger of it and durability.effect.brokenBlockPass through. Read by the native server at boot.' },
  { key: 'combatCritNotice',        label: 'Critical hit notices',  type: 'bool',   group: 'Gameplay', help: 'On (default, also when unset): while alduinakDamageFormulaSettings.enabled is true a critical hit tells the attacking player "Critical hit! <damage> damage." and the player hit "You took a critical hit: <damage> damage.". Off keeps both off. Read by the gamemode when it loads: Build gamemode only or a restart applies a change.' },
  { key: 'craftedExtrasTemperRules', label: 'Temper rules in vanilla menus', type: 'bool', group: 'Gameplay', help: 'On: a temper done in the vanilla menu follows the recipe\'s rank gates and rank cap and costs one craft of fatigue. Off: it takes the materials only, up to Legendary, as in 1.0. Unset (default): on while alduinakDamageFormulaSettings has enabled or durability.enabled true, off otherwise. Read at boot.' },
  { key: 'chatRanges',              label: 'Chat ranges',           type: 'json',   group: 'Gameplay', help: 'Audible ranges in game units: { whisper, low, say, wide, shout }. Provided keys override the defaults.' },
  { key: 'voiceChat',               label: 'Voice chat',            type: 'json',   group: 'Gameplay', help: 'LiveKit proximity voice: { enabled, url, apiKey, apiSecret, room, rangeUnits }. rangeUnits = MAX talk range (defaults to chatRanges.shout); speakers pick their range between chatRanges.whisper and this with V + mousewheel.' },
  { key: 'maskName',                label: 'Mask name',             type: 'text',   group: 'Gameplay', help: 'Name shown for a /mask-ed player. Default "Masked Person".' },
  { key: 'introduceCooldownMs',     label: 'Introduce cooldown (ms)', type: 'number', group: 'Gameplay', help: 'Min gap between /introduce prompts to the same target. Default 10000.' },
  { key: 'masteryKitGold',          label: 'Profession kit gold',   type: 'number', group: 'Gameplay', help: 'Gold every profession\'s starting kit carries on top of its items, alchemists included; a character that got gold from Starting items gets none. Default 50; 0 turns it off. Read at boot.' },
  { key: 'gatheringVeinTotal',      label: 'Ore per vein',          type: 'number', group: 'Gameplay', help: 'Ore collections every mining vein holds, one per pickaxe strike. Default 6; 0 uses each record\'s own total (3 for vanilla veins). Read at boot.' },
  { key: 'gatheringVeinRespawnMinutes', label: 'Vein regrow (minutes)', type: 'number', group: 'Gameplay', help: 'Minutes after the first ore taken until the whole vein is back at once. Default 1440 (24 h); 0 keeps the default. Read at boot.' },
  { key: 'gatheringVeinRegenMinutes', label: 'Vein gradual regrow (minutes)', type: 'number', group: 'Gameplay', help: 'Leave empty (default) for the whole vein at once. Set: one ore collection grows back per that many minutes instead. Read at boot.' },
  { key: 'gatheringProduceYield',   label: 'Beehive yield',         type: 'json',   group: 'Gameplay', help: '{ "<container editor id>": { "<item editor id>": count } } handed over on E instead of the container record\'s contents. Default: occupied and vacant beehives and apiaries give 2 Bee Honeycomb, 2 Bee and 2 Beehive Husk, back after an hour (gatheringProduceContainers). Read at boot.' },
  { key: 'gatheringPickMinutes',    label: 'Nirnroot and critter regrow (minutes)', type: 'number', group: 'Gameplay', help: 'Minutes a picked nirnroot or a caught bee or firefly stays gone for everyone. Default 30. Read at boot.' },
  { key: 'huntingSkinPlayers',      label: 'Hunters skin player bodies', type: 'select', group: 'Gameplay', options: ['crouch', 'interact', 'off'], help: 'A hunter with the hunting knife skins a dead player\'s body during the respawn wait, or the body a PK left, for Human Flesh, maybe a Human Heart and on a Khajiit maybe a Khajiit Pelt; an own body then vanishes as if looted (the player respawns at once with their pack), a PK body also gives the skinner everything it holds, keys and letters included. crouch (default, also when unset): the body opens a Search and Skin menu for them (a client without the menu skins on crouch and interact), anyone else searches. interact: every interact skins, as on an animal. off: never. Read at boot.' },
  { key: 'huntingHumanHeartChance', label: 'Human heart chance',    type: 'number', group: 'Gameplay', placeholder: '0.1', help: 'Chance, 0 to 1, that skinning a player\'s body also gives a Human Heart. Default 0.1. Read at boot.' },
  { key: 'huntingKhajiitPeltChance', label: 'Khajiit pelt chance',  type: 'number', group: 'Gameplay', placeholder: '0.2', help: 'Chance, 0 to 1, that skinning a player\'s body that looks Khajiit (KhajiitRace or its vampire form, a PK body included) also gives a Khajiit Pelt (AldKhajiitPelt, plugin r24). Default 0.2. Read at boot.' },
  { key: 'gatheringAlchemistFloraDiscount', label: 'Alchemist flora discount', type: 'number', group: 'Gameplay', help: 'Extra share of the fatigue an alchemist (Novice or better) saves when picking alchemy flora (flowers, mushrooms, herbs and nirnroot that give an ingredient, never crops), on top of the farmer price for their rank they already pay. Default 0 (off); 0.5 halves it again. Read at boot.' },
  { key: 'needsSurvivalModeFlag',   label: 'Survival mode flag on clients', type: 'bool', group: 'Gameplay', help: 'On (default): clients set the Creation\'s Survival_ModeToggle (SRVT) to 1 with each needs update. The HUD polls that global every frame and draws the red penalty segments on the stamina and magicka bars only under it; off, the HUD clears them once after each load whatever the penalty globals hold. Survival_ModeEnabled is script-only, nothing in the engine reads it. On also gives every client the engine\'s Survival extras: arrows, bolts and the lockpick weigh their record weight and armour cards show a Warmth line. Read at boot.' },

  // Races
  { key: 'racialPassives', label: 'Racial passives', type: 'json', group: 'Races', help: 'The only place race numbers live; resistances, stats, claws and powers stay in the plugin. { enabled (default true; false makes every race neutral), aliases { "<race>": "<entry race>" } over the built-in vampire and child races, races { "<RaceEditorId>": { fatigueCostMult, hungerRateMult, coldRateMult, warmth, rawMeatSafe, freezingWaterImmune, startingItems [{ baseId, count }] } }, startItemsSince (epoch ms or a date, default the 1.0 launch: a character created since then gets missed start items at its next login), selfCheck ("off" default, "log" logs each client race report as check ok or MISMATCH, "resync" also asks the client once per spawn to redo its race sync), powers { "<SPEL editor id>": { cooldownHours (real hours from the last use, counting offline, default 0), consumeOnMiss (default false), commandAnimal { ... } } }: a player\'s cast of a listed power is refused while its cooldown runs, and a power whose effect block is not built yet (Command Animal until RC6) is always refused }. A missing multiplier is 1, warmth 0, a flag false; empty makes every race neutral. The Test Nord entry is { "warmth": 25, "freezingWaterImmune": false }: Nords grow cold like anyone and carry Survival\'s 25 warmth. Start items come once per profile and slot when creation finishes and never count as starter gold. Not protected: Migrate settings carries it to live, so remove quick-test powers first. Read at boot; see docs_racial_passives.md.' },

  // Survival (every key read at boot; see the Survival section of docs_roleplay_creations_and_needs.md)
  { key: 'survivalEnabled',            label: 'Survival enabled',               type: 'bool',   group: 'Survival', help: 'Master switch for cold, afflictions, raw meat, diseases and the body rules. Default off. Off, or a part switched off, undoes at each login what an earlier session granted. Protected: Migrate settings never copies it to live; set it there by hand once survival is signed off.' },
  { key: 'survivalRespawnHealthPoints', label: 'Respawn health points',         type: 'number', group: 'Survival', placeholder: '1', help: 'Health points a respawn after a death (temple, afterlife arrival) and a staff revive wake with, measured against the race base health (100, an Orc 150); magicka and stamina keep theirs. Default 1; 0 uses the share below.' },
  { key: 'survivalRespawnHealth',      label: 'Respawn health share',           type: 'number', group: 'Survival', placeholder: '0.01', help: 'Share of base health a respawn wakes with when the points above are 0, above 0 up to 1. Default 0.01; 1 turns the respawn rule off, whatever the points say.' },
  { key: 'survivalCarryWeightSpell',   label: 'Carry weight ability',           type: 'json',   group: 'Survival', help: 'Editor id or "hex:Plugin" desc of the carry weight ability, in quotes. Default "Survival_abLowerCarryWeightSpell" (carry weight 150); "" turns it off.' },
  { key: 'survivalNoHealthRegen',      label: 'No health regeneration',         type: 'bool',   group: 'Survival', help: 'On (default): every character holds AldSurvival_AbNoHealthRegen (plugin r27a); potions, food and Restoration still heal. Off removes it at login. The server-side refusal of a client that regenerates anyway is Health regen multiplier 0 (Gameplay).' },
  { key: 'survivalFreezingWater',      label: 'Freezing water',                 type: 'bool',   group: 'Survival', help: 'On (default): grants AldSurvival_FreezingWaterDamage once (it hurts only while swimming in a freezing area) and adds the freezing water cold. Off removes both.' },
  { key: 'survivalFoodPoisoningChance', label: 'Raw meat poisoning chance',     type: 'number', group: 'Survival', placeholder: '0.5', help: 'Chance raw meat gives food poisoning, times (1 - disease resistance); 0 to 1, 0 turns it off. Races with racialPassives rawMeatSafe never get it.' },
  { key: 'survivalFoodPoisoningHours', label: 'Food poisoning hours',           type: 'number', group: 'Survival', placeholder: '24', help: 'Real hours food poisoning lasts, offline included.' },
  { key: 'survivalRawMeatExtra',       label: 'Extra raw meat',                 type: 'json',   group: 'Survival', help: 'More raw meat foods: editor ids, hex ids or descs, on top of Survival_FoodRawMeat and the hunting meats. Default [].' },
  { key: 'survivalCure',               label: 'What cures',                     type: 'select', group: 'Survival', options: ['cureDiseaseOrHealth', 'cureDisease'], help: 'cureDiseaseOrHealth (default): a Cure Disease potion or a potion restoring the minimum health below cures diseases, food poisoning and afflictions. cureDisease: Cure Disease potions only. Shrines never cure.' },
  { key: 'survivalCureMinHealth',      label: 'Curing potion health',           type: 'number', group: 'Survival', placeholder: '25', help: 'Health a potion must restore to cure under cureDiseaseOrHealth.' },
  { key: 'survivalColdEnabled',        label: 'Cold enabled',                   type: 'bool',   group: 'Survival', help: 'On (default): cold and warmth run while survival is on. Off takes the cold stage ability back at login.' },
  { key: 'survivalColdHoursToNumb',    label: 'Hours to Numb',                  type: 'number', group: 'Survival', placeholder: '1.3334', help: 'Real hours in which cold level 20 with no warmth fills the bar at an area rate of 1, 20 times slower than single player. 0.02 only for quick tests, never on live.' },
  { key: 'survivalColdLevelMult',      label: 'Cold level multiplier',          type: 'number', group: 'Survival', placeholder: '50', help: 'Survival_ColdLevelMult: with no warmth, cold rises this much per cold level in survivalColdHoursToNumb hours (50 x level 20 = 1000).' },
  { key: 'survivalColdStages',         label: 'Cold stages',                    type: 'json',   group: 'Survival', help: 'Cold at which Comfortable, Chilly, Very Cold, Freezing and Numb begin: five rising numbers below 1000. Default [50, 120, 300, 500, 800].' },
  { key: 'survivalColdStart',          label: 'Starting cold',                  type: 'number', group: 'Survival', placeholder: '55', help: 'Cold of a new character, after a respawn and after an admin reset; offline warming stops here.' },
  { key: 'survivalColdLevels',         label: 'Cold levels',                    type: 'json',   group: 'Survival', help: '{ warm, cool, freezing, chillyInterior, warmNight, coolNight, freezingNight, rain, snow, blizzard, freezingWater } merged over the default { 0, 3, 6, 6, 1, 2, 4, 3, 6, 10, 30 }.' },
  { key: 'survivalColdAreaRate',       label: 'Cold area rates',                type: 'json',   group: 'Survival', help: '{ warm, cool, freezing, chillyInterior } merged over the default { 1, 1, 0.6667, 0.6667 }: cold gain multiplier of the area class the character stands in, not applied in freezing water. The default makes a freezing blizzard night with no warmth take one hour from no cold to Freezing; 0.8333 for freezing and chillyInterior puts the hour on a snowy night (a blizzard night 48 minutes); 1 everywhere is Survival\'s plain pace (40 minutes).' },
  { key: 'survivalColdLevelCaps',      label: 'Cold level caps',                type: 'json',   group: 'Survival', help: 'Cold level that lets cold reach stages 1 to 5: five rising numbers. Default [1, 4, 7, 10, 13].' },
  { key: 'survivalNightHours',         label: 'Night hours',                    type: 'json',   group: 'Survival', help: '[after, before] on the game clock. Default [19, 7].' },
  { key: 'survivalRegionClimate',      label: 'Region climate',                 type: 'json',   group: 'Survival', help: '{ "<weather region id>": "warm" | "cool" | "freezing" | "none" } merged over the 45 classed regions of survivalClimate.ts.' },
  { key: 'survivalWorldClimate',       label: 'World climate',                  type: 'json',   group: 'Survival', help: '{ "<worldspace editor id>": class } merged over the defaults (Whiterun, Windhelm, Solitude and Markarth worlds cool, Riften warm, the realms none).' },
  { key: 'survivalHighAltitude',       label: 'High altitude',                  type: 'json',   group: 'Survival', help: '{ freezingZ, "<weather region id>": height }: freezing above the height. Default { "freezingZ": 19000, "fallForest": 15150 }.' },
  { key: 'survivalColdWarmPerMinute',  label: 'Warming per minute',             type: 'number', group: 'Survival', placeholder: '40', help: 'Cold lost per minute above the cold level\'s cap, not within 10 s of a hit.' },
  { key: 'survivalColdOfflineWarmPerHour', label: 'Offline warming per hour',   type: 'number', group: 'Survival', placeholder: '1000', help: 'Cold lost per hour logged out, down to the starting cold.' },
  { key: 'survivalHeatRadius',         label: 'Heat radius',                    type: 'number', group: 'Survival', placeholder: '580', help: 'Units from a fire, forge or cooking pot within which a character standing still warms.' },
  { key: 'survivalHeatRestore',        label: 'Heat warming',                   type: 'number', group: 'Survival', placeholder: '75', help: 'Cold taken off by a heat source every check.' },
  { key: 'survivalHeatCheckSeconds',   label: 'Heat check (s)',                 type: 'number', group: 'Survival', placeholder: '6', help: 'Seconds between heat checks, 1 or more.' },
  { key: 'survivalHeatStillUnits',     label: 'Heat stand-still distance',      type: 'number', group: 'Survival', placeholder: '48', help: 'A character who moved less than this since the last check counts as standing still.' },
  { key: 'survivalHeatExtraBases',     label: 'Extra heat sources',             type: 'json',   group: 'Survival', help: 'Base editor ids or descs that also warm. Read by misc/gen-heat-sources.py, which writes heatSources.ts: rerun it and Build server after a change. Default [].' },
  { key: 'survivalHeatKeywords',       label: 'Heat furniture keywords',        type: 'json',   group: 'Survival', help: 'Furniture keywords that warm, read by misc/gen-heat-sources.py like the key above. Default ["CraftingCookpot", "AldCraftingKiln"].' },
  { key: 'survivalWarmth',             label: 'Warmth ratings',                 type: 'json',   group: 'Survival', help: '{ normal, warm, cold: [body, head, hands, feet], torch, cloak, max, maxReduction } merged over { [27, 18, 13, 13], [54, 29, 24, 24], [17, 8, 7, 7], 50, 0, 206, 0.85 }: max warmth cuts cold gain by maxReduction.' },
  { key: 'survivalWarmthTable',        label: 'Warmth table',                   type: 'bool',   group: 'Survival', help: 'On (default): the server rates the pieces the engine\'s Survival keywords leave out from armorWarmth.ts (misc/gen-armor-warmth.py): mod pieces and enchanted copies count as warm or cold like the comparable base game piece, and cloaks, capes, collars, scarves and masks add 3 to 20 warmth. Off counts keywords only, as the item cards show.' },
  { key: 'survivalHotFoodWarmth',      label: 'Hot food warmth',                type: 'number', group: 'Survival', placeholder: '25', help: 'Warmth a hot meal gives.' },
  { key: 'survivalHotFoodWarmthMinutes', label: 'Hot food minutes',             type: 'number', group: 'Survival', placeholder: '100', help: 'Real minutes a hot meal keeps warming.' },
  { key: 'survivalSpellHitCold',       label: 'Spell hit cold',                 type: 'number', group: 'Survival', placeholder: '30', help: 'Cold a frost spell hit adds (up to Freezing) and a fire spell hit takes off (down to Chilly).' },
  { key: 'survivalColdOnHit',          label: 'Cold from creature hits',        type: 'json',   group: 'Survival', help: '{ "<race editor id fragment>": cold } added by an unblocked hit of those races, merged over { "frostbitespider": 30, "falmer": 30 }.' },
  { key: 'survivalColdKills',          label: 'Cold kills',                     type: 'bool',   group: 'Survival', help: 'On kills a character at cold 1000. Default off.' },
  { key: 'survivalColdStageAbilities', label: 'Cold stage abilities',           type: 'bool',   group: 'Survival', help: 'On (default): the Survival_ColdStage0..5 ability of the current stage (speed, lockpicking, the frost shader).' },
  { key: 'survivalColdHealthPenalty',  label: 'Cold health penalty',            type: 'bool',   group: 'Survival', help: 'On (default): clients shrink maximum health by the cold share, like hunger and fatigue do stamina and magicka.' },
  { key: 'survivalColdMaxHealthPenalty', label: 'Cold health penalty cap',      type: 'number', group: 'Survival', placeholder: '0.8', help: 'Largest share of maximum health cold takes, 0 to 1, so Numb keeps a fifth of the bar.' },
  { key: 'survivalColdHealthScale',    label: 'Cold health scale (native)',     type: 'bool',   group: 'Survival', help: 'On also writes private.healthScale for the native health scale (NV4), which this build does not read yet. Default off.' },
  { key: 'survivalFreezingWaterWorlds', label: 'Freezing water worlds',         type: 'json',   group: 'Survival', help: 'Worldspace editor ids whose water always freezes, besides freezing areas and cold interiors. Default ["DLC1HunterHQWorld"].' },
  { key: 'survivalAfflictions',        label: 'Afflictions',                    type: 'json',   group: 'Survival', help: '{ weakened, addled, frostbitten: { chance 0 to 1, tickMinutes } | false } merged over { 0.2, 15 }, { 0.3, 30 }, { 0.16, 5 }, rolled at Starving, Debilitated and Numb; false turns them all off.' },
  { key: 'survivalAfflictionHours',    label: 'Affliction hours',               type: 'number', group: 'Survival', placeholder: '24', help: 'Real hours an affliction lasts, offline included (0.1 only for quick tests).' },
  { key: 'survivalDiseasesEnabled',    label: 'Diseases enabled',               type: 'bool',   group: 'Survival', help: 'On (default): creature hits and contagion give diseases while survival is on. Off gives none and removes those held at login.' },
  { key: 'survivalDiseases',           label: 'Disease overrides',              type: 'json',   group: 'Survival', help: '{ "<disease id>": false | { name, contagious, stageHours [h1, h2] } } over the 27 catalog diseases of survivalDiseases.ts; false drops one. Default {}.' },
  { key: 'survivalDiseaseCarriers',    label: 'Disease carriers',               type: 'json',   group: 'Survival', help: '{ "<race editor id fragment>": false | { chance 0 to 1, diseases [ids] } } merged over the 20 default carriers (skeever, wolf, bear, troll, draugr, ...).' },
  { key: 'survivalDiseaseCarrierExclude', label: 'Races that carry nothing',    type: 'json',   group: 'Survival', help: 'Race editor id fragments no carrier matches. Default ["werewolf", "werebear"].' },
  { key: 'survivalDiseaseStageHours',  label: 'Disease stage hours',            type: 'json',   group: 'Survival', help: '[stage 1 to 2, stage 2 to 3] in real hours, offline included; stage 3 stays until cured. Default [84, 84] ([0.05, 0.05] only for quick tests).' },
  { key: 'survivalMaxDiseases',        label: 'Most diseases at once',          type: 'number', group: 'Survival', placeholder: '4', help: 'Diseases a character can hold at once; an admin may give more.' },
  { key: 'survivalContagionChance',    label: 'Contagion chance',               type: 'number', group: 'Survival', placeholder: '0.05', help: 'Chance per contagious disease a client reports near the player, times (1 - disease resistance); the server rolls once per confirmed disease and pair per cooldown; 0 turns contagion off.' },
  { key: 'survivalContagionRange',     label: 'Contagion range',                type: 'number', group: 'Survival', placeholder: '150', help: 'Units within which the client counts a carrier; empty uses the chat whisper range (chatRanges.whisper).' },
  { key: 'survivalContagionCheckSeconds', label: 'Contagion check (s)',         type: 'number', group: 'Survival', placeholder: '60', help: 'Seconds between one client\'s contagion checks, 1 or more; the server accepts one report per player per this less 5 s.' },
  { key: 'survivalContagionCooldownMinutes', label: 'Contagion cooldown (min)', type: 'number', group: 'Survival', placeholder: '30', help: 'Minutes before the same disease and pair of players roll again; 0 rolls at every report.' },

  // Interactions (capture / carry / search / trade tunables)
  { key: 'captureInteractMaxDistance', label: 'Capture range',                 type: 'number', group: 'Interactions', help: 'Max game-units distance to start a capture/carry. Default 256.' },
  { key: 'captureConsentTimeoutMs',    label: 'Capture consent timeout (ms)',  type: 'number', group: 'Interactions', help: 'How long a capture/carry consent prompt waits for an answer. Default 20000.' },
  { key: 'captureConsentCooldownMs',   label: 'Capture consent cooldown (ms)', type: 'number', group: 'Interactions', help: 'Min gap before prompting the same target again. Default 15000.' },
  { key: 'tradeMaxDistance',           label: 'Trade range',                   type: 'number', group: 'Interactions', help: 'Max game-units distance both players must stay within to trade. Default 1024.' },
  { key: 'tradeInviteTtlMs',           label: 'Trade invite TTL (ms)',         type: 'number', group: 'Interactions', help: 'Pending trade invites auto-cancel after this. Default 60000.' },
  { key: 'tradeInviteCooldownMs',      label: 'Trade invite cooldown (ms)',    type: 'number', group: 'Interactions', help: 'Min gap between trade invites per initiator to target. Default 30000.' },
  { key: 'searchStartMaxDistance',     label: 'Search start range',            type: 'number', group: 'Interactions', help: 'Max game-units distance to start searching a player. Default 256.' },
  { key: 'searchKeepMaxDistance',      label: 'Search keep range',             type: 'number', group: 'Interactions', help: 'The search window closes once the pair drift further apart than this. Default 512.' },
  { key: 'searchConsentTimeoutMs',     label: 'Search consent timeout (ms)',   type: 'number', group: 'Interactions', help: 'How long a search consent prompt waits for an answer. Default 20000.' },
  { key: 'searchConsentCooldownMs',    label: 'Search consent cooldown (ms)',  type: 'number', group: 'Interactions', help: 'Min gap before prompting the same target again. Default 15000.' },
  { key: 'keySplitOnLogin',            label: 'Split old key stacks at login', type: 'bool',   group: 'Interactions', help: 'Splits a stack of property keys cut before keys were numbered (Property Key (TAG) xN) into N numbered keys when its holder logs in. Keep off until the client with the new SkyrimPlatformImpl.dll has shipped and named keys stay separate in game; an older client merges the split keys back and put/take fails. Read at startup. Default off.' },
  { key: 'bountyBoardCostGold',        label: 'Bounty board post cost',        type: 'number', group: 'Interactions', help: 'Gold taken for pinning a notice on a Missives board. 0 = free. Default 25.' },
  { key: 'bountyBoardStashBase',       label: 'Bounty board strongbox base',   type: 'text',   group: 'Interactions', placeholder: '10aad2:Skyrim.esm', help: 'CONT base (hex:Plugin desc or load-order id) placed at each board to hold the posting fees. A strongbox of another base is replaced at the next start, contents moved over. Default the vanilla strongbox. Read at startup.' },
  { key: 'bountyBoardStashLift',       label: 'Bounty board strongbox lift',   type: 'json',   group: 'Interactions', help: '{ "<board name>": units } the strongbox stands above the visible board\'s foot, over the built-in lifts (Winterhold 40, Dawnstar 49, Falkreath 17; misc/bounty-stash-lift.py measures them). A box off its spot is moved at the next start, contents kept. Read at startup.' },
  { key: 'writingEnabled',             label: 'Writeable letters and books',   type: 'bool',   group: 'Interactions', help: 'Lets players write letters, journals and books. Keep off until the plugin with the writing records is in the manifest and players have re-downloaded. Read at startup. Default off.' },

  // Data & storage
  { key: 'dataDir',        label: 'Data directory', type: 'text',   group: 'Data & storage', placeholder: 'data', help: 'ESMs / ESPs / UI / scripts.' },
  { key: 'gamemodePath',   label: 'Gamemode path',  type: 'text',   group: 'Data & storage', placeholder: './gamemode.js' },
  { key: 'databaseDriver', label: 'Database driver', type: 'select', group: 'Data & storage', options: ['file', 'mongodb', 'zip', 'migration'] },
  { key: 'databaseName',   label: 'Database name',   type: 'text',   group: 'Data & storage', placeholder: 'world', help: 'File DB folder / Mongo db name. Characters live in <name>/changeForms.' },
  { key: 'databaseUri',    label: 'Database URI',    type: 'secret', group: 'Data & storage', placeholder: 'mongodb://user:pass@127.0.0.1:27017', help: 'Mongo connection string (mongodb driver only). Embeds credentials - keep it secret.' },
  { key: 'logDir',         label: 'Log directory',   type: 'text',   group: 'Data & storage', placeholder: 'C:\\logs', help: 'Where chat.log and service logs are written. Overridden by the ALDUINAK_LOG_DIR env var.' },

  // Complex / nested (rendered as JSON sub-editors)
  { key: 'loadOrder',     label: 'Load order',     type: 'json', group: 'Advanced', help: 'Array of ESM/ESP filenames in order.' },
  { key: 'archives',      label: 'BSA archives',   type: 'json', group: 'Advanced', help: 'Array of BSA filenames to load.' },
  { key: 'startPoints',   label: 'Start points',   type: 'json', group: 'Advanced', help: 'Spawn points: [{ pos:[x,y,z], worldOrCell, angleZ }].' },
  { key: 'reloot',        label: 'Reloot timers',  type: 'json', group: 'Advanced', help: 'Record type → ms before respawn. FLOR and TREE are the alchemy plants: 1800000 (30 min) live, one hour when unset. Native server, read at boot.' },
  { key: 'forbiddenReloot', label: 'Forbidden reloot', type: 'json', group: 'Advanced', help: 'Record types that never respawn; wins over Reloot timers. Item types (MISC, WEAP, ...) and FLOR/TREE: plugin-placed refs cannot be taken at all. "LIGH": placed torches and lanterns. "CONT": an emptied container never refills, so storage chests stay player-only. Native server, read at boot.' },
  { key: 'emptyContainers', label: 'Empty containers', type: 'bool', group: 'Advanced', help: 'On (default, also when unset): chests, barrels and other placed containers from every plugin open without their plugin loot; items players put in stay, and containers already filled keep what they hold. Off: a container that never received anything gets its plugin loot on its next open. NPCs and corpses are unaffected. Native server, read at boot.' },
  { key: 'containerLootBaseIds', label: 'Containers keeping loot', type: 'json', group: 'Advanced', help: 'CONT base records (numbers, "0x..." strings or "hex:File.esp") that keep their plugin loot while Empty containers is on. Default []. Native server, read at boot.' },
  { key: 'untouchableBaseIds', label: 'Untouchable objects', type: 'json', group: 'Advanced', help: 'Base form ids nobody can activate (numbers or "0x..." strings). Default: the vanilla coin purses, loose salmon, Stones of Barenziah and wall torch sconces. [] disables.' },
  { key: 'exteriorScriptAllowlist', label: 'Exterior scripts', type: 'json', group: 'Advanced', help: 'Vanilla Papyrus scripts that still run on exterior objects; every other vanilla script is stripped there. Default: ["default2StateActivator", "NorLever01SCRIPT"] so lever-driven exterior gates open. [] strips them too. Native server, read at boot.' },
  { key: 'leverLinks', label: 'Lever links', type: 'json', group: 'Advanced', help: 'Levers wired to their gate through markers the server never loads: [{ levers:["hex:File.esp", ...], target:"hex:File.esp", all?, openAnim?, closeAnim? }]. all: every lever pulled once before the target moves. A DOOR target toggles isOpen, anything else plays open/close. Default: Soljund\'s Sinkhole portcullis. [] disables. Read at boot.' },
  { key: 'blockedSpells',  label: 'Blocked spells',  type: 'json', group: 'Advanced', help: 'Spell form ids players may not cast (numbers or "0x..." strings), e.g. racial powers.' },
  { key: 'adminProfileIds', label: 'Admin profile IDs', type: 'json', group: 'Advanced', help: 'Master-api profile ids granted in-game admin chat commands. Array of numbers.' },
  { key: 'adminRoleIds',    label: 'Admin Discord roles', type: 'json', group: 'Advanced', help: 'Legacy flat list of Discord role ids (strings) that get the in-game admin menu (Insert) and the server console. Roles here but in no adminRoles tier get full (senior) rights. Example: ["1521259484859863190"].' },
  { key: 'adminRoles',      label: 'Admin role tiers',    type: 'json', group: 'Advanced', help: 'Discord role ids per tier: { senior:[...], developer:[...], gm:[...] }. senior and gm have every power; developer has everything except Kick and Ban. Tier lists win over adminRoleIds; precedence senior > developer > gm.' },
  { key: 'adminTeleportLocations', label: 'Admin teleport locations', type: 'json', group: 'Advanced', help: 'Admin panel Teleport tab: [{ name, cellOrWorldDesc: "hexId:Plugin.esm", pos:[x,y,z], rot:[x,y,z], kind? }]. Listed before the built-in map-marker locations; bad entries are dropped at boot.' },
  { key: 'npcSettings',   label: 'NPC settings',   type: 'json', group: 'Advanced' },
  { key: 'metricsAuth',   label: 'Metrics auth',   type: 'json', group: 'Advanced', help: '{ user, password } for /metrics basic auth.' },
  { key: 'damageMultFormulaSettings', label: 'Damage formula', type: 'json', group: 'Advanced' },
  { key: 'alduinakDamageFormulaSettings', label: 'Rebalance and durability', type: 'json', group: 'Advanced', help: 'The generated block of misc/combat-settings/generate.py (staged in alduinak-r13/live); change design.json and run the generator again rather than editing rows here, and after every plugin change. Empty (default) = combat as in 1.0. enabled (default false): the rebalance formula prices weapon hits by row damage against worn DT, with playerHitCap (45), the sneak, power and rate limit rules and blockStamina { perArmorWeight 0.006, weightCap 115 }. durability.enabled (default false), independent of enabled: worn weapons, armor and shields wear on hits (durability.wear, HP tables per row), lose effect below durability.effect.kneeCondition (0.5), show a name tag (durability.nameTag { showAtFull true, brokenLabel "Broken" }) and are repaired at the benches. durability.repair { unitsPerMissing { weapon 0.5, cuirass 0.5, other 1 }: share one set of temper materials restores; fallbackMaterial { kind: { row: form key } } for items without a temper recipe; requireProfessionRank (false); fatigue (0); anyBench (false: workbench armor and shields, grindstone weapons); menuOnActivate (true); chatCommand ("repair", "" for none); lowNoticeBelow (0.25) }. effectModifiers (default true): OneHandedMod, TwoHandedMod, MarksmanMod and BlockMod of abilities and diseases scale weapon damage and blocking while either switch is on, so a hungry player\'s block leaks. A wrong value rejects the whole block with error lines at boot and the server runs as without it. Protected: Migrate settings never carries it to live. With plugin r28, enabled false is not a return to 1.0 numbers. Read at boot; see docs_server_configuration_reference.md.' },
  { key: 'additionalServerSettings',  label: 'Additional settings (GitHub)', type: 'json', group: 'Advanced' },
  { key: 'discordAuth',   label: 'Discord auth',   type: 'json', group: 'Advanced', help: 'Discord bot integration: { botToken, guilds:[{ guildId, banRoleId, eventLogChannelId }] }. Holds a bot token - keep it secret.' },
  { key: 'discordAlertKinds', label: 'Discord alert kinds', type: 'json', group: 'Advanced', help: 'Alert kinds posted to the event log channel. Default ["admin","execute","ticket"]; add "keyword" or "login" to post them. Deaths are never posted. Read at boot.' },
]

// backend .env - the Express backend configuration. `secret: true` masks the value.
const backendEnv = [
  // HTTP / relay
  { key: 'PORT',         label: 'HTTP port',       type: 'number', group: 'HTTP & relay', help: 'Express backend listen port.' },
  { key: 'WS_PORT',      label: 'WS relay port',   type: 'number', group: 'HTTP & relay', help: 'In-game chat + admin console relay.' },
  { key: 'RELAY_SECRET', label: 'Relay secret',    type: 'secret', group: 'HTTP & relay', help: 'Shared between the relay, the gamemode, and this manager.' },

  // Game server connection
  { key: 'SKYMP_HOST',     label: 'Game server host', type: 'text',   group: 'Game server', placeholder: '127.0.0.1' },
  { key: 'SERVER_ADDRESS', label: 'Public address',   type: 'text',   group: 'Game server', help: 'Public IP advertised to external clients.' },

  // Server metadata (reported to the launcher)
  { key: 'SERVER_GAMEMODE',    label: 'Gamemode label',   type: 'text',   group: 'Server metadata', placeholder: 'Roleplay' },

  // Discord OAuth & bot
  { key: 'DISCORD_CLIENT_ID',     label: 'Discord client ID',     type: 'text',   group: 'Discord' },
  { key: 'DISCORD_CLIENT_SECRET', label: 'Discord client secret', type: 'secret', group: 'Discord' },
  { key: 'DISCORD_REDIRECT_URI',  label: 'Discord redirect URI',  type: 'text',   group: 'Discord' },
  { key: 'DISCORD_BOT_TOKEN',     label: 'Discord bot token',     type: 'secret', group: 'Discord' },
  { key: 'DISCORD_GUILD_ID',      label: 'Discord guild ID',      type: 'text',   group: 'Discord' },

  // Admin dashboard
  { key: 'DASHBOARD_PORT',        label: 'Dashboard port',        type: 'number', group: 'Admin dashboard' },
  { key: 'DASHBOARD_PUBLIC_URL',  label: 'Dashboard public URL',  type: 'text',   group: 'Admin dashboard' },
  { key: 'DASHBOARD_API_BASE_URL', label: 'Dashboard API base URL', type: 'text', group: 'Admin dashboard' },
  { key: 'DISCORD_DASHBOARD_REDIRECT_URI', label: 'Dashboard redirect URI', type: 'text', group: 'Admin dashboard' },
  { key: 'DASHBOARD_DISCORD_IDS', label: 'Dashboard Discord IDs', type: 'text',   group: 'Admin dashboard', help: 'Comma-separated Discord user IDs.' },
  { key: 'WEBSITE_URL',           label: 'Website URL',           type: 'text',   group: 'Admin dashboard' },

  // Metrics

  // Access control
  { key: 'LAUNCH_CHECK_ENFORCE',   label: 'Enforce launch check', type: 'bool', group: 'Access control', help: 'Refuse connections whose launcher did not verify client files + load order. Unset = enforced (the default); only Off disables it, for players on pre-check launcher builds.' },
  { key: 'BAN_LOG_DIR',            label: 'Ban log directory', type: 'text', group: 'Access control', help: 'Where ban.log and faction.log are written. Empty = the default logs folder.' },

  // Client updates
  { key: 'CLIENT_FILES_DIR',      label: 'Client files directory', type: 'text',  group: 'Client updates', help: 'Folder holding the served client files. Empty = build/client-files.' },

  // CI & tooling
  { key: 'ALDUINAK_GH_TOKEN',     label: 'GitHub token (PAT)',    type: 'secret', group: 'CI & tooling', help: 'PAT with actions:write - powers the manager CI Rebuild (workflow dispatch).' },

  // Web Server Manager (dashboard) and its AlduinakManager agent
  { key: 'MANAGER_AGENT_PORT',        label: 'Agent port',          type: 'number', group: 'Web manager', help: 'Loopback port of the AlduinakManager service. Default 4003. Restart the backend and the agent after a change.' },
  { key: 'MANAGER_AGENT_SECRET',      label: 'Agent secret',        type: 'secret', group: 'Web manager', help: 'Shared secret the backend signs agent calls with, at least 32 characters.' },
  { key: 'MANAGER_LOG_DIR',           label: 'Manager log folder',  type: 'text',   group: 'Web manager', placeholder: 'C:\\logs\\manager', help: 'Web jobs, their logs, the busy lock and the audit files.' },
  { key: 'MANAGER_AUDIT_WEBHOOK_URL', label: 'Audit Discord webhook', type: 'secret', group: 'Web manager', help: 'Optional private staff channel webhook that mirrors manager actions and failed logins.' },
]

module.exports = { serverSettings, backendEnv }
