'use strict'

const { loc } = require('./loc')

const serverSettings = [
  // Identity
  { key: 'name',        label: loc('serverField.name.label'),  type: 'text',   group: loc('settingsGroup.identity'), help: loc('serverField.name.help') },
  { key: 'port',        label: loc('serverField.port.label'), type: 'number', group: loc('settingsGroup.identity'), help: loc('serverField.port.help') },
  { key: 'maxPlayers',  label: loc('serverField.maxPlayers.label'), type: 'number', group: loc('settingsGroup.identity'), help: loc('serverField.maxPlayers.help') },
  { key: 'playerSlots', label: loc('serverField.playerSlots.label'),   type: 'number', group: loc('settingsGroup.identity'), help: loc('serverField.playerSlots.help') },
  { key: 'queueGraceMs', label: loc('serverField.queueGraceMs.label'), type: 'number', group: loc('settingsGroup.identity'), help: loc('serverField.queueGraceMs.help') },
  { key: 'queueStaffBypass', label: loc('serverField.queueStaffBypass.label'), type: 'bool', group: loc('settingsGroup.identity'), help: loc('serverField.queueStaffBypass.help') },
  { key: 'lang',        label: loc('serverField.lang.label'),     type: 'select', group: loc('settingsGroup.identity'),
    options: ['english', 'russian', 'german', 'french', 'spanish', 'italian', 'polish', 'chinese', 'japanese'] },

  // Networking
  { key: 'listenHost',   label: loc('serverField.listenHost.label'),    type: 'text', group: loc('settingsGroup.networking'), placeholder: '0.0.0.0', help: loc('serverField.listenHost.help') },
  { key: 'uiListenHost', label: loc('serverField.uiListenHost.label'), type: 'text', group: loc('settingsGroup.networking'), placeholder: '0.0.0.0', help: loc('serverField.uiListenHost.help') },
  { key: 'ip',           label: loc('serverField.ip.label'),  type: 'text', group: loc('settingsGroup.networking'), help: loc('serverField.ip.help') },

  // Mode & auth
  { key: 'offlineMode', label: loc('serverField.offlineMode.label'),  type: 'bool', group: loc('settingsGroup.modeAuth'), help: loc('serverField.offlineMode.help') },
  { key: 'master',      label: loc('serverField.master.label'),    type: 'text', group: loc('settingsGroup.modeAuth'), help: loc('serverField.master.help') },
  { key: 'masterKey',   label: loc('serverField.masterKey.label'),    type: 'secret', group: loc('settingsGroup.modeAuth'), help: loc('serverField.masterKey.help') },
  { key: 'masterApiAuthToken', label: loc('serverField.masterApiAuthToken.label'), type: 'secret', group: loc('settingsGroup.modeAuth'), help: loc('serverField.masterApiAuthToken.help') },
  { key: 'enableConsoleCommandsForAll', label: loc('serverField.enableConsoleCommandsForAll.label'), type: 'bool', group: loc('settingsGroup.modeAuth'), help: loc('serverField.enableConsoleCommandsForAll.help') },

  // Gameplay
  { key: 'characterSelect',         label: loc('serverField.characterSelect.label'),      type: 'bool',   group: loc('settingsGroup.gameplay'), help: loc('serverField.characterSelect.help') },
  { key: 'characterSelectMaxCharacters', label: loc('serverField.characterSelectMaxCharacters.label'),   type: 'number', group: loc('settingsGroup.gameplay'), help: loc('serverField.characterSelectMaxCharacters.help') },
  { key: 'npcEnabled',              label: loc('serverField.npcEnabled.label'),          type: 'bool',   group: loc('settingsGroup.gameplay') },
  { key: 'npcCorpseWatch',          label: loc('serverField.npcCorpseWatch.label'), type: 'bool', group: loc('settingsGroup.gameplay'), help: loc('serverField.npcCorpseWatch.help') },
  { key: 'masteryResetsPerCharacter', label: loc('serverField.masteryResetsPerCharacter.label'), type: 'number', group: loc('settingsGroup.gameplay'), placeholder: '1', help: loc('serverField.masteryResetsPerCharacter.help') },
  { key: 'masteryHourBank',         label: loc('serverField.masteryHourBank.label'),  type: 'number', group: loc('settingsGroup.gameplay'), placeholder: '2', help: loc('serverField.masteryHourBank.help') },
  { key: 'masteryBankOffline',      label: loc('serverField.masteryBankOffline.label'), type: 'bool', group: loc('settingsGroup.gameplay'), help: loc('serverField.masteryBankOffline.help') },
  { key: 'masterySlots',            label: loc('serverField.masterySlots.label'), type: 'json', group: loc('settingsGroup.gameplay'), help: loc('serverField.masterySlots.help') },
  { key: 'masterySlotKits',         label: loc('serverField.masterySlotKits.label'),         type: 'bool',   group: loc('settingsGroup.gameplay'), help: loc('serverField.masterySlotKits.help') },
  { key: 'securityAlertChannelId',  label: loc('serverField.securityAlertChannelId.label'), type: 'text', group: loc('settingsGroup.gameplay'), help: loc('serverField.securityAlertChannelId.help') },
  { key: 'needsFatigueEnabled',     label: loc('serverField.needsFatigueEnabled.label'),       type: 'bool', group: loc('settingsGroup.gameplay'), help: loc('serverField.needsFatigueEnabled.help') },
  { key: 'needsFatigueOfflinePerHour', label: loc('serverField.needsFatigueOfflinePerHour.label'), type: 'number', group: loc('settingsGroup.gameplay'), placeholder: '1', help: loc('serverField.needsFatigueOfflinePerHour.help') },
  { key: 'torchBurnMinutes',        label: loc('serverField.torchBurnMinutes.label'),  type: 'number', group: loc('settingsGroup.gameplay'), placeholder: '15', help: loc('serverField.torchBurnMinutes.help') },
  { key: 'goldAlertThreshold',      label: loc('serverField.goldAlertThreshold.label'),  type: 'number', group: loc('settingsGroup.gameplay'), placeholder: '5000', help: loc('serverField.goldAlertThreshold.help') },
  { key: 'isPapyrusHotReloadEnabled', label: loc('serverField.isPapyrusHotReloadEnabled.label'),  type: 'bool',   group: loc('settingsGroup.gameplay'), help: loc('serverField.isPapyrusHotReloadEnabled.help') },
  { key: 'locale',                  label: loc('serverField.locale.label'),           type: 'text',   group: loc('settingsGroup.gameplay'), help: loc('serverField.locale.help') },
  { key: 'manaclesFormId',          label: loc('serverField.manaclesFormId.label'),         type: 'text',   group: loc('settingsGroup.gameplay'), help: loc('serverField.manaclesFormId.help') },
  { key: 'captiveAnimEvent',        label: loc('serverField.captiveAnimEvent.label'),    type: 'text',   group: loc('settingsGroup.gameplay'), help: loc('serverField.captiveAnimEvent.help') },
  { key: 'carrierAnimEvent',        label: loc('serverField.carrierAnimEvent.label'),    type: 'text',   group: loc('settingsGroup.gameplay'), help: loc('serverField.carrierAnimEvent.help') },
  { key: 'startingItems',           label: loc('serverField.startingItems.label'),        type: 'json',   group: loc('settingsGroup.gameplay'), help: loc('serverField.startingItems.help') },
  { key: 'playersInheritBaseSpells', label: loc('serverField.playersInheritBaseSpells.label'), type: 'bool', group: loc('settingsGroup.gameplay'), help: loc('serverField.playersInheritBaseSpells.help') },
  { key: 'logoutGraceMs',           label: loc('serverField.logoutGraceMs.label'),     type: 'number', group: loc('settingsGroup.gameplay'), help: loc('serverField.logoutGraceMs.help') },
  { key: 'respawnSeconds',          label: loc('serverField.respawnSeconds.label'),       type: 'number', group: loc('settingsGroup.gameplay'), help: loc('serverField.respawnSeconds.help') },
  { key: 'afkKickMinutes',          label: loc('serverField.afkKickMinutes.label'),    type: 'number', group: loc('settingsGroup.gameplay'), help: loc('serverField.afkKickMinutes.help') },
  { key: 'afkWarnMinutes',          label: loc('serverField.afkWarnMinutes.label'), type: 'number', group: loc('settingsGroup.gameplay'), help: loc('serverField.afkWarnMinutes.help') },
  { key: 'regenerationMultiplier',  label: loc('serverField.regenerationMultiplier.label'),      type: 'number', group: loc('settingsGroup.gameplay'), help: loc('serverField.regenerationMultiplier.help') },
  { key: 'healthRegenerationMultiplier', label: loc('serverField.healthRegenerationMultiplier.label'), type: 'number', group: loc('settingsGroup.gameplay'), help: loc('serverField.healthRegenerationMultiplier.help') },
  { key: 'npcBlockedDamageShare',   label: loc('serverField.npcBlockedDamageShare.label'), type: 'number', group: loc('settingsGroup.gameplay'), help: loc('serverField.npcBlockedDamageShare.help') },
  { key: 'combatCritNotice',        label: loc('serverField.combatCritNotice.label'),  type: 'bool',   group: loc('settingsGroup.gameplay'), help: loc('serverField.combatCritNotice.help') },
  { key: 'craftedExtrasTemperRules', label: loc('serverField.craftedExtrasTemperRules.label'), type: 'bool', group: loc('settingsGroup.gameplay'), help: loc('serverField.craftedExtrasTemperRules.help') },
  { key: 'chatRanges',              label: loc('serverField.chatRanges.label'),           type: 'json',   group: loc('settingsGroup.gameplay'), help: loc('serverField.chatRanges.help') },
  { key: 'voiceChat',               label: loc('serverField.voiceChat.label'),            type: 'json',   group: loc('settingsGroup.gameplay'), help: loc('serverField.voiceChat.help') },
  { key: 'maskName',                label: loc('serverField.maskName.label'),             type: 'text',   group: loc('settingsGroup.gameplay'), help: loc('serverField.maskName.help') },
  { key: 'introduceCooldownMs',     label: loc('serverField.introduceCooldownMs.label'), type: 'number', group: loc('settingsGroup.gameplay'), help: loc('serverField.introduceCooldownMs.help') },
  { key: 'masteryKitGold',          label: loc('serverField.masteryKitGold.label'),   type: 'number', group: loc('settingsGroup.gameplay'), help: loc('serverField.masteryKitGold.help') },
  { key: 'gatheringVeinTotal',      label: loc('serverField.gatheringVeinTotal.label'),          type: 'number', group: loc('settingsGroup.gameplay'), help: loc('serverField.gatheringVeinTotal.help') },
  { key: 'gatheringVeinRespawnMinutes', label: loc('serverField.gatheringVeinRespawnMinutes.label'), type: 'number', group: loc('settingsGroup.gameplay'), help: loc('serverField.gatheringVeinRespawnMinutes.help') },
  { key: 'gatheringVeinRegenMinutes', label: loc('serverField.gatheringVeinRegenMinutes.label'), type: 'number', group: loc('settingsGroup.gameplay'), help: loc('serverField.gatheringVeinRegenMinutes.help') },
  { key: 'gatheringProduceYield',   label: loc('serverField.gatheringProduceYield.label'),         type: 'json',   group: loc('settingsGroup.gameplay'), help: loc('serverField.gatheringProduceYield.help') },
  { key: 'gatheringPickMinutes',    label: loc('serverField.gatheringPickMinutes.label'), type: 'number', group: loc('settingsGroup.gameplay'), help: loc('serverField.gatheringPickMinutes.help') },
  { key: 'huntingSkinPlayers',      label: loc('serverField.huntingSkinPlayers.label'), type: 'select', group: loc('settingsGroup.gameplay'), options: ['crouch', 'interact', 'off'], help: loc('serverField.huntingSkinPlayers.help') },
  { key: 'huntingHumanHeartChance', label: loc('serverField.huntingHumanHeartChance.label'),    type: 'number', group: loc('settingsGroup.gameplay'), placeholder: '0.1', help: loc('serverField.huntingHumanHeartChance.help') },
  { key: 'huntingKhajiitPeltChance', label: loc('serverField.huntingKhajiitPeltChance.label'),  type: 'number', group: loc('settingsGroup.gameplay'), placeholder: '0.2', help: loc('serverField.huntingKhajiitPeltChance.help') },
  { key: 'gatheringAlchemistFloraDiscount', label: loc('serverField.gatheringAlchemistFloraDiscount.label'), type: 'number', group: loc('settingsGroup.gameplay'), help: loc('serverField.gatheringAlchemistFloraDiscount.help') },
  { key: 'needsSurvivalModeFlag',   label: loc('serverField.needsSurvivalModeFlag.label'), type: 'bool', group: loc('settingsGroup.gameplay'), help: loc('serverField.needsSurvivalModeFlag.help') },

  // Races
  { key: 'racialPassives', label: loc('serverField.racialPassives.label'), type: 'json', group: loc('settingsGroup.races'), help: loc('serverField.racialPassives.help') },

  // Survival (every key read at boot; see the Survival section of docs_roleplay_creations_and_needs.md)
  { key: 'survivalEnabled',            label: loc('serverField.survivalEnabled.label'),               type: 'bool',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalEnabled.help') },
  { key: 'survivalRespawnHealthPoints', label: loc('serverField.survivalRespawnHealthPoints.label'),         type: 'number', group: loc('settingsGroup.survival'), placeholder: '1', help: loc('serverField.survivalRespawnHealthPoints.help') },
  { key: 'survivalRespawnHealth',      label: loc('serverField.survivalRespawnHealth.label'),           type: 'number', group: loc('settingsGroup.survival'), placeholder: '0.01', help: loc('serverField.survivalRespawnHealth.help') },
  { key: 'survivalCarryWeightSpell',   label: loc('serverField.survivalCarryWeightSpell.label'),           type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalCarryWeightSpell.help') },
  { key: 'survivalNoHealthRegen',      label: loc('serverField.survivalNoHealthRegen.label'),       type: 'bool',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalNoHealthRegen.help') },
  { key: 'survivalFreezingWater',      label: loc('serverField.survivalFreezingWater.label'),                 type: 'bool',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalFreezingWater.help') },
  { key: 'survivalFreezingWaterDamage', label: loc('serverField.survivalFreezingWaterDamage.label'),     type: 'number', group: loc('settingsGroup.survival'), placeholder: '0.25', help: loc('serverField.survivalFreezingWaterDamage.help') },
  { key: 'survivalFoodPoisoningChance', label: loc('serverField.survivalFoodPoisoningChance.label'),     type: 'number', group: loc('settingsGroup.survival'), placeholder: '0.5', help: loc('serverField.survivalFoodPoisoningChance.help') },
  { key: 'survivalFoodPoisoningHours', label: loc('serverField.survivalFoodPoisoningHours.label'),           type: 'number', group: loc('settingsGroup.survival'), placeholder: '24', help: loc('serverField.survivalFoodPoisoningHours.help') },
  { key: 'survivalRawMeatExtra',       label: loc('serverField.survivalRawMeatExtra.label'),                 type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalRawMeatExtra.help') },
  { key: 'survivalCure',               label: loc('serverField.survivalCure.label'),                     type: 'select', group: loc('settingsGroup.survival'), options: ['cureDiseaseOrHealth', 'cureDisease'], help: loc('serverField.survivalCure.help') },
  { key: 'survivalCureMinHealth',      label: loc('serverField.survivalCureMinHealth.label'),           type: 'number', group: loc('settingsGroup.survival'), placeholder: '25', help: loc('serverField.survivalCureMinHealth.help') },
  { key: 'survivalColdEnabled',        label: loc('serverField.survivalColdEnabled.label'),                   type: 'bool',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalColdEnabled.help') },
  { key: 'survivalColdHoursToNumb',    label: loc('serverField.survivalColdHoursToNumb.label'),                  type: 'number', group: loc('settingsGroup.survival'), placeholder: '1.3334', help: loc('serverField.survivalColdHoursToNumb.help') },
  { key: 'survivalColdLevelMult',      label: loc('serverField.survivalColdLevelMult.label'),          type: 'number', group: loc('settingsGroup.survival'), placeholder: '50', help: loc('serverField.survivalColdLevelMult.help') },
  { key: 'survivalColdStages',         label: loc('serverField.survivalColdStages.label'),                    type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalColdStages.help') },
  { key: 'survivalColdStart',          label: loc('serverField.survivalColdStart.label'),                  type: 'number', group: loc('settingsGroup.survival'), placeholder: '55', help: loc('serverField.survivalColdStart.help') },
  { key: 'survivalColdLevels',         label: loc('serverField.survivalColdLevels.label'),                    type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalColdLevels.help') },
  { key: 'survivalColdAreaRate',       label: loc('serverField.survivalColdAreaRate.label'),                type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalColdAreaRate.help') },
  { key: 'survivalColdLevelCaps',      label: loc('serverField.survivalColdLevelCaps.label'),                type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalColdLevelCaps.help') },
  { key: 'survivalNightHours',         label: loc('serverField.survivalNightHours.label'),                    type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalNightHours.help') },
  { key: 'survivalRegionClimate',      label: loc('serverField.survivalRegionClimate.label'),                 type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalRegionClimate.help') },
  { key: 'survivalWorldClimate',       label: loc('serverField.survivalWorldClimate.label'),                  type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalWorldClimate.help') },
  { key: 'survivalHighAltitude',       label: loc('serverField.survivalHighAltitude.label'),                  type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalHighAltitude.help') },
  { key: 'survivalColdWarmPerMinute',  label: loc('serverField.survivalColdWarmPerMinute.label'),             type: 'number', group: loc('settingsGroup.survival'), placeholder: '40', help: loc('serverField.survivalColdWarmPerMinute.help') },
  { key: 'survivalColdOfflineWarmPerHour', label: loc('serverField.survivalColdOfflineWarmPerHour.label'),   type: 'number', group: loc('settingsGroup.survival'), placeholder: '1000', help: loc('serverField.survivalColdOfflineWarmPerHour.help') },
  { key: 'survivalHeatRadius',         label: loc('serverField.survivalHeatRadius.label'),                    type: 'number', group: loc('settingsGroup.survival'), placeholder: '580', help: loc('serverField.survivalHeatRadius.help') },
  { key: 'survivalHeatRestore',        label: loc('serverField.survivalHeatRestore.label'),                   type: 'number', group: loc('settingsGroup.survival'), placeholder: '75', help: loc('serverField.survivalHeatRestore.help') },
  { key: 'survivalHeatCheckSeconds',   label: loc('serverField.survivalHeatCheckSeconds.label'),                 type: 'number', group: loc('settingsGroup.survival'), placeholder: '6', help: loc('serverField.survivalHeatCheckSeconds.help') },
  { key: 'survivalHeatStillUnits',     label: loc('serverField.survivalHeatStillUnits.label'),      type: 'number', group: loc('settingsGroup.survival'), placeholder: '48', help: loc('serverField.survivalHeatStillUnits.help') },
  { key: 'survivalHeatExtraBases',     label: loc('serverField.survivalHeatExtraBases.label'),             type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalHeatExtraBases.help') },
  { key: 'survivalHeatKeywords',       label: loc('serverField.survivalHeatKeywords.label'),        type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalHeatKeywords.help') },
  { key: 'survivalWarmth',             label: loc('serverField.survivalWarmth.label'),                 type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalWarmth.help') },
  { key: 'survivalWarmthTable',        label: loc('serverField.survivalWarmthTable.label'),                   type: 'bool',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalWarmthTable.help') },
  { key: 'survivalHotFoodWarmth',      label: loc('serverField.survivalHotFoodWarmth.label'),                type: 'number', group: loc('settingsGroup.survival'), placeholder: '25', help: loc('serverField.survivalHotFoodWarmth.help') },
  { key: 'survivalHotFoodWarmthMinutes', label: loc('serverField.survivalHotFoodWarmthMinutes.label'),             type: 'number', group: loc('settingsGroup.survival'), placeholder: '100', help: loc('serverField.survivalHotFoodWarmthMinutes.help') },
  { key: 'survivalSpellHitCold',       label: loc('serverField.survivalSpellHitCold.label'),                 type: 'number', group: loc('settingsGroup.survival'), placeholder: '30', help: loc('serverField.survivalSpellHitCold.help') },
  { key: 'survivalColdOnHit',          label: loc('serverField.survivalColdOnHit.label'),        type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalColdOnHit.help') },
  { key: 'survivalColdKills',          label: loc('serverField.survivalColdKills.label'),                     type: 'bool',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalColdKills.help') },
  { key: 'survivalColdStageAbilities', label: loc('serverField.survivalColdStageAbilities.label'),           type: 'bool',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalColdStageAbilities.help') },
  { key: 'survivalColdHealthPenalty',  label: loc('serverField.survivalColdHealthPenalty.label'),            type: 'bool',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalColdHealthPenalty.help') },
  { key: 'survivalColdMaxHealthPenalty', label: loc('serverField.survivalColdMaxHealthPenalty.label'),      type: 'number', group: loc('settingsGroup.survival'), placeholder: '0.8', help: loc('serverField.survivalColdMaxHealthPenalty.help') },
  { key: 'survivalColdHealthScale',    label: loc('serverField.survivalColdHealthScale.label'),     type: 'bool',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalColdHealthScale.help') },
  { key: 'survivalFreezingWaterWorlds', label: loc('serverField.survivalFreezingWaterWorlds.label'),         type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalFreezingWaterWorlds.help') },
  { key: 'survivalAfflictions',        label: loc('serverField.survivalAfflictions.label'),                    type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalAfflictions.help') },
  { key: 'survivalAfflictionHours',    label: loc('serverField.survivalAfflictionHours.label'),               type: 'number', group: loc('settingsGroup.survival'), placeholder: '24', help: loc('serverField.survivalAfflictionHours.help') },
  { key: 'survivalDiseasesEnabled',    label: loc('serverField.survivalDiseasesEnabled.label'),               type: 'bool',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalDiseasesEnabled.help') },
  { key: 'survivalDiseases',           label: loc('serverField.survivalDiseases.label'),              type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalDiseases.help') },
  { key: 'survivalDiseaseCarriers',    label: loc('serverField.survivalDiseaseCarriers.label'),               type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalDiseaseCarriers.help') },
  { key: 'survivalDiseaseCarrierExclude', label: loc('serverField.survivalDiseaseCarrierExclude.label'),    type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalDiseaseCarrierExclude.help') },
  { key: 'survivalDiseaseStageHours',  label: loc('serverField.survivalDiseaseStageHours.label'),            type: 'json',   group: loc('settingsGroup.survival'), help: loc('serverField.survivalDiseaseStageHours.help') },
  { key: 'survivalMaxDiseases',        label: loc('serverField.survivalMaxDiseases.label'),          type: 'number', group: loc('settingsGroup.survival'), placeholder: '4', help: loc('serverField.survivalMaxDiseases.help') },
  { key: 'survivalContagionChance',    label: loc('serverField.survivalContagionChance.label'),               type: 'number', group: loc('settingsGroup.survival'), placeholder: '0.05', help: loc('serverField.survivalContagionChance.help') },
  { key: 'survivalContagionRange',     label: loc('serverField.survivalContagionRange.label'),                type: 'number', group: loc('settingsGroup.survival'), placeholder: '150', help: loc('serverField.survivalContagionRange.help') },
  { key: 'survivalContagionCheckSeconds', label: loc('serverField.survivalContagionCheckSeconds.label'),         type: 'number', group: loc('settingsGroup.survival'), placeholder: '60', help: loc('serverField.survivalContagionCheckSeconds.help') },
  { key: 'survivalContagionCooldownMinutes', label: loc('serverField.survivalContagionCooldownMinutes.label'), type: 'number', group: loc('settingsGroup.survival'), placeholder: '30', help: loc('serverField.survivalContagionCooldownMinutes.help') },

  // Interactions (capture / carry / search / trade tunables)
  { key: 'captureInteractMaxDistance', label: loc('serverField.captureInteractMaxDistance.label'),                 type: 'number', group: loc('settingsGroup.interactions'), help: loc('serverField.captureInteractMaxDistance.help') },
  { key: 'captureConsentTimeoutMs',    label: loc('serverField.captureConsentTimeoutMs.label'),  type: 'number', group: loc('settingsGroup.interactions'), help: loc('serverField.captureConsentTimeoutMs.help') },
  { key: 'captureConsentCooldownMs',   label: loc('serverField.captureConsentCooldownMs.label'), type: 'number', group: loc('settingsGroup.interactions'), help: loc('serverField.captureConsentCooldownMs.help') },
  { key: 'tradeMaxDistance',           label: loc('serverField.tradeMaxDistance.label'),                   type: 'number', group: loc('settingsGroup.interactions'), help: loc('serverField.tradeMaxDistance.help') },
  { key: 'tradeInviteTtlMs',           label: loc('serverField.tradeInviteTtlMs.label'),         type: 'number', group: loc('settingsGroup.interactions'), help: loc('serverField.tradeInviteTtlMs.help') },
  { key: 'tradeInviteCooldownMs',      label: loc('serverField.tradeInviteCooldownMs.label'),    type: 'number', group: loc('settingsGroup.interactions'), help: loc('serverField.tradeInviteCooldownMs.help') },
  { key: 'searchStartMaxDistance',     label: loc('serverField.searchStartMaxDistance.label'),            type: 'number', group: loc('settingsGroup.interactions'), help: loc('serverField.searchStartMaxDistance.help') },
  { key: 'searchKeepMaxDistance',      label: loc('serverField.searchKeepMaxDistance.label'),             type: 'number', group: loc('settingsGroup.interactions'), help: loc('serverField.searchKeepMaxDistance.help') },
  { key: 'searchConsentTimeoutMs',     label: loc('serverField.searchConsentTimeoutMs.label'),   type: 'number', group: loc('settingsGroup.interactions'), help: loc('serverField.searchConsentTimeoutMs.help') },
  { key: 'searchConsentCooldownMs',    label: loc('serverField.searchConsentCooldownMs.label'),  type: 'number', group: loc('settingsGroup.interactions'), help: loc('serverField.searchConsentCooldownMs.help') },
  { key: 'keySplitOnLogin',            label: loc('serverField.keySplitOnLogin.label'), type: 'bool',   group: loc('settingsGroup.interactions'), help: loc('serverField.keySplitOnLogin.help') },
  { key: 'bountyBoardCostGold',        label: loc('serverField.bountyBoardCostGold.label'),        type: 'number', group: loc('settingsGroup.interactions'), help: loc('serverField.bountyBoardCostGold.help') },
  { key: 'bountyBoardStashBase',       label: loc('serverField.bountyBoardStashBase.label'),   type: 'text',   group: loc('settingsGroup.interactions'), placeholder: '9424c:Skyrim.esm', help: loc('serverField.bountyBoardStashBase.help') },
  { key: 'bountyBoardStashLift',       label: loc('serverField.bountyBoardStashLift.label'),   type: 'json',   group: loc('settingsGroup.interactions'), help: loc('serverField.bountyBoardStashLift.help') },
  { key: 'writingEnabled',             label: loc('serverField.writingEnabled.label'),   type: 'bool',   group: loc('settingsGroup.interactions'), help: loc('serverField.writingEnabled.help') },

  // Data & storage
  { key: 'dataDir',        label: loc('serverField.dataDir.label'), type: 'text',   group: loc('settingsGroup.dataStorage'), placeholder: 'data', help: loc('serverField.dataDir.help') },
  { key: 'gamemodePath',   label: loc('serverField.gamemodePath.label'),  type: 'text',   group: loc('settingsGroup.dataStorage'), placeholder: './gamemode.js' },
  { key: 'gamemodeHotReload', label: loc('serverField.gamemodeHotReload.label'), type: 'bool', group: loc('settingsGroup.dataStorage'), help: loc('serverField.gamemodeHotReload.help') },
  { key: 'databaseDriver', label: loc('serverField.databaseDriver.label'), type: 'select', group: loc('settingsGroup.dataStorage'), options: ['file', 'mongodb'] },
  { key: 'databaseName',   label: loc('serverField.databaseName.label'),   type: 'text',   group: loc('settingsGroup.dataStorage'), placeholder: 'world', help: loc('serverField.databaseName.help') },
  { key: 'databaseUri',    label: loc('serverField.databaseUri.label'),    type: 'secret', group: loc('settingsGroup.dataStorage'), placeholder: 'mongodb://user:pass@127.0.0.1:27017', help: loc('serverField.databaseUri.help') },
  { key: 'logDir',         label: loc('serverField.logDir.label'),   type: 'text',   group: loc('settingsGroup.dataStorage'), placeholder: 'C:\\logs', help: loc('serverField.logDir.help') },

  // Complex / nested (rendered as JSON sub-editors)
  { key: 'loadOrder',     label: loc('serverField.loadOrder.label'),     type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.loadOrder.help') },
  { key: 'archives',      label: loc('serverField.archives.label'),   type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.archives.help') },
  { key: 'startPoints',   label: loc('serverField.startPoints.label'),   type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.startPoints.help') },
  { key: 'reloot',        label: loc('serverField.reloot.label'),  type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.reloot.help') },
  { key: 'forbiddenReloot', label: loc('serverField.forbiddenReloot.label'), type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.forbiddenReloot.help') },
  { key: 'emptyContainers', label: loc('serverField.emptyContainers.label'), type: 'bool', group: loc('settingsGroup.advanced'), help: loc('serverField.emptyContainers.help') },
  { key: 'containerLootBaseIds', label: loc('serverField.containerLootBaseIds.label'), type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.containerLootBaseIds.help') },
  { key: 'exteriorScriptAllowlist', label: loc('serverField.exteriorScriptAllowlist.label'), type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.exteriorScriptAllowlist.help') },
  { key: 'leverLinks', label: loc('serverField.leverLinks.label'), type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.leverLinks.help') },
  { key: 'blockedSpells',  label: loc('serverField.blockedSpells.label'),  type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.blockedSpells.help') },
  { key: 'adminProfileIds', label: loc('serverField.adminProfileIds.label'), type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.adminProfileIds.help') },
  { key: 'adminRoleIds',    label: loc('serverField.adminRoleIds.label'), type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.adminRoleIds.help') },
  { key: 'adminRoles',      label: loc('serverField.adminRoles.label'),    type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.adminRoles.help') },
  { key: 'adminTeleportLocations', label: loc('serverField.adminTeleportLocations.label'), type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.adminTeleportLocations.help') },
  { key: 'npcSettings',   label: loc('serverField.npcSettings.label'),   type: 'json', group: loc('settingsGroup.advanced') },
  { key: 'metricsAuth',   label: loc('serverField.metricsAuth.label'),   type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.metricsAuth.help') },
  { key: 'damageMultFormulaSettings', label: loc('serverField.damageMultFormulaSettings.label'), type: 'json', group: loc('settingsGroup.advanced') },
  { key: 'alduinakDamageFormulaSettings', label: loc('serverField.alduinakDamageFormulaSettings.label'), type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.alduinakDamageFormulaSettings.help') },
  { key: 'combatTrace', label: loc('serverField.combatTrace.label'), type: 'bool', group: loc('settingsGroup.advanced'), help: loc('serverField.combatTrace.help') },
  { key: 'maxMovementSpeed', label: loc('serverField.maxMovementSpeed.label'), type: 'number', group: loc('settingsGroup.advanced'), placeholder: '2048', help: loc('serverField.maxMovementSpeed.help') },
  { key: 'enforceMovementSpeed', label: loc('serverField.enforceMovementSpeed.label'), type: 'bool', group: loc('settingsGroup.advanced'), help: loc('serverField.enforceMovementSpeed.help') },
  { key: 'maxActivateDistance', label: loc('serverField.maxActivateDistance.label'), type: 'number', group: loc('settingsGroup.advanced'), placeholder: '1024', help: loc('serverField.maxActivateDistance.help') },
  { key: 'enforceActivateDistance', label: loc('serverField.enforceActivateDistance.label'), type: 'bool', group: loc('settingsGroup.advanced'), help: loc('serverField.enforceActivateDistance.help') },
  { key: 'meleeSlack', label: loc('serverField.meleeSlack.label'), type: 'number', group: loc('settingsGroup.advanced'), placeholder: '400', help: loc('serverField.meleeSlack.help') },
  { key: 'enforceMeleeReach', label: loc('serverField.enforceMeleeReach.label'), type: 'bool', group: loc('settingsGroup.advanced'), help: loc('serverField.enforceMeleeReach.help') },
  { key: 'maxShotDistance', label: loc('serverField.maxShotDistance.label'), type: 'number', group: loc('settingsGroup.advanced'), placeholder: '8192', help: loc('serverField.maxShotDistance.help') },
  { key: 'enforceShotDistance', label: loc('serverField.enforceShotDistance.label'), type: 'bool', group: loc('settingsGroup.advanced'), help: loc('serverField.enforceShotDistance.help') },
  { key: 'spellHitWindow', label: loc('serverField.spellHitWindow.label'), type: 'number', group: loc('settingsGroup.advanced'), placeholder: '10', help: loc('serverField.spellHitWindow.help') },
  { key: 'enforceSpellHitWindow', label: loc('serverField.enforceSpellHitWindow.label'), type: 'bool', group: loc('settingsGroup.advanced'), help: loc('serverField.enforceSpellHitWindow.help') },
  { key: 'maxAppearanceNameLength', label: loc('serverField.maxAppearanceNameLength.label'), type: 'number', group: loc('settingsGroup.advanced'), placeholder: '64', help: loc('serverField.maxAppearanceNameLength.help') },
  { key: 'maxAppearanceTints', label: loc('serverField.maxAppearanceTints.label'), type: 'number', group: loc('settingsGroup.advanced'), placeholder: '128', help: loc('serverField.maxAppearanceTints.help') },
  { key: 'enforceAppearanceLimits', label: loc('serverField.enforceAppearanceLimits.label'), type: 'bool', group: loc('settingsGroup.advanced'), help: loc('serverField.enforceAppearanceLimits.help') },
  { key: 'additionalServerSettings',  label: loc('serverField.additionalServerSettings.label'), type: 'json', group: loc('settingsGroup.advanced') },
  { key: 'discordAuth',   label: loc('serverField.discordAuth.label'),   type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.discordAuth.help') },
  { key: 'discordAlertKinds', label: loc('serverField.discordAlertKinds.label'), type: 'json', group: loc('settingsGroup.advanced'), help: loc('serverField.discordAlertKinds.help') },
]

// backend .env - the Express backend configuration. `secret: true` masks the value.
const backendEnv = [
  // HTTP / relay
  { key: 'PORT',         label: loc('envField.PORT.label'),       type: 'number', group: loc('settingsGroup.httpRelay'), help: loc('envField.PORT.help') },
  { key: 'WS_PORT',      label: loc('envField.WS_PORT.label'),   type: 'number', group: loc('settingsGroup.httpRelay'), help: loc('envField.WS_PORT.help') },
  { key: 'RELAY_SECRET', label: loc('envField.RELAY_SECRET.label'),    type: 'secret', group: loc('settingsGroup.httpRelay'), help: loc('envField.RELAY_SECRET.help') },

  // Game server connection
  { key: 'SKYMP_HOST',     label: loc('envField.SKYMP_HOST.label'), type: 'text',   group: loc('settingsGroup.gameServer'), placeholder: '127.0.0.1' },
  { key: 'SERVER_ADDRESS', label: loc('envField.SERVER_ADDRESS.label'),   type: 'text',   group: loc('settingsGroup.gameServer'), help: loc('envField.SERVER_ADDRESS.help') },

  // Server metadata (reported to the launcher)
  { key: 'SERVER_GAMEMODE',    label: loc('envField.SERVER_GAMEMODE.label'),   type: 'text',   group: loc('settingsGroup.serverMetadata'), placeholder: 'Roleplay' },

  // Discord OAuth & bot
  { key: 'DISCORD_CLIENT_ID',     label: loc('envField.DISCORD_CLIENT_ID.label'),     type: 'text',   group: loc('settingsGroup.discord') },
  { key: 'DISCORD_CLIENT_SECRET', label: loc('envField.DISCORD_CLIENT_SECRET.label'), type: 'secret', group: loc('settingsGroup.discord') },
  { key: 'DISCORD_REDIRECT_URI',  label: loc('envField.DISCORD_REDIRECT_URI.label'),  type: 'text',   group: loc('settingsGroup.discord') },
  { key: 'DISCORD_BOT_TOKEN',     label: loc('envField.DISCORD_BOT_TOKEN.label'),     type: 'secret', group: loc('settingsGroup.discord') },
  { key: 'DISCORD_GUILD_ID',      label: loc('envField.DISCORD_GUILD_ID.label'),      type: 'text',   group: loc('settingsGroup.discord') },

  // Admin dashboard
  { key: 'DASHBOARD_PORT',        label: loc('envField.DASHBOARD_PORT.label'),        type: 'number', group: loc('settingsGroup.adminDashboard') },
  { key: 'DASHBOARD_PUBLIC_URL',  label: loc('envField.DASHBOARD_PUBLIC_URL.label'),  type: 'text',   group: loc('settingsGroup.adminDashboard') },
  { key: 'DASHBOARD_API_BASE_URL', label: loc('envField.DASHBOARD_API_BASE_URL.label'), type: 'text', group: loc('settingsGroup.adminDashboard') },
  { key: 'DISCORD_DASHBOARD_REDIRECT_URI', label: loc('envField.DISCORD_DASHBOARD_REDIRECT_URI.label'), type: 'text', group: loc('settingsGroup.adminDashboard') },
  { key: 'DASHBOARD_DISCORD_IDS', label: loc('envField.DASHBOARD_DISCORD_IDS.label'), type: 'text',   group: loc('settingsGroup.adminDashboard'), help: loc('envField.DASHBOARD_DISCORD_IDS.help') },
  { key: 'WEBSITE_URL',           label: loc('envField.WEBSITE_URL.label'),           type: 'text',   group: loc('settingsGroup.adminDashboard') },

  // Metrics

  // Access control
  { key: 'LAUNCH_CHECK_ENFORCE',   label: loc('envField.LAUNCH_CHECK_ENFORCE.label'), type: 'bool', group: loc('settingsGroup.accessControl'), help: loc('envField.LAUNCH_CHECK_ENFORCE.help') },
  { key: 'BAN_LOG_DIR',            label: loc('envField.BAN_LOG_DIR.label'), type: 'text', group: loc('settingsGroup.accessControl'), help: loc('envField.BAN_LOG_DIR.help') },

  // Client updates
  { key: 'CLIENT_FILES_DIR',      label: loc('envField.CLIENT_FILES_DIR.label'), type: 'text',  group: loc('settingsGroup.clientUpdates'), help: loc('envField.CLIENT_FILES_DIR.help') },

  // CI & tooling
  { key: 'ALDUINAK_GH_TOKEN',     label: loc('envField.ALDUINAK_GH_TOKEN.label'),    type: 'secret', group: loc('settingsGroup.ciTooling'), help: loc('envField.ALDUINAK_GH_TOKEN.help') },

  // Web Server Manager (dashboard) and its AlduinakManager agent
  { key: 'MANAGER_AGENT_PORT',        label: loc('envField.MANAGER_AGENT_PORT.label'),          type: 'number', group: loc('settingsGroup.webManager'), help: loc('envField.MANAGER_AGENT_PORT.help') },
  { key: 'MANAGER_AGENT_SECRET',      label: loc('envField.MANAGER_AGENT_SECRET.label'),        type: 'secret', group: loc('settingsGroup.webManager'), help: loc('envField.MANAGER_AGENT_SECRET.help') },
  { key: 'MANAGER_LOG_DIR',           label: loc('envField.MANAGER_LOG_DIR.label'),  type: 'text',   group: loc('settingsGroup.webManager'), placeholder: 'C:\\logs\\manager', help: loc('envField.MANAGER_LOG_DIR.help') },
  { key: 'MANAGER_AUDIT_WEBHOOK_URL', label: loc('envField.MANAGER_AUDIT_WEBHOOK_URL.label'), type: 'secret', group: loc('settingsGroup.webManager'), help: loc('envField.MANAGER_AUDIT_WEBHOOK_URL.help') },
]

module.exports = { serverSettings, backendEnv }
